[package]
name = "foundry-test-utils"
description = "Foundry testing utilities"
publish = false

version.workspace = true
edition.workspace = true

[dependencies]
foundry-common.workspace = true
foundry-compilers = { workspace = true, features = ["project-util"] }

fd-lock = "4.0.0"
once_cell = "1"
regex = "1"
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
rand.workspace = true

[features]
# feature for integration tests that test external projects
external-integration-tests = []

[lints]
workspace = true
