/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** An account that needs to be created during the genesis block. */
export interface GenesisAccount {
  /** Account secret key */
  secretKey: string
  /** Account balance */
  balance: bigint
}
export interface BlockOptions {
  /** The parent block's hash */
  parentHash?: Buffer
  /** The block's beneficiary */
  beneficiary?: Buffer
  /** The state's root hash */
  stateRoot?: Buffer
  /** The block's difficulty */
  difficulty?: bigint
  /** The block's number */
  number?: bigint
  /** The block's gas limit */
  gasLimit?: bigint
  /** The block's timestamp */
  timestamp?: bigint
  /** The block's extra data */
  extraData?: Buffer
  /** The block's mix hash (or prevrandao) */
  mixHash?: Buffer
  /** The block's nonce */
  nonce?: Buffer
  /** The block's base gas fee */
  baseFee?: bigint
  /** The block's withdrawals */
  withdrawals?: Array<Withdrawal>
  /** Blob gas was added by EIP-4844 and is ignored in older headers. */
  blobGas?: BlobGas
  /**
   * The hash tree root of the parent beacon block for the given execution
   * block (EIP-4788).
   */
  parentBeaconBlockRoot?: Buffer
  /**
   * The commitment hash calculated for a list of [EIP-7685] data requests.
   *
   * [EIP-7685]: https://eips.ethereum.org/EIPS/eip-7685
   */
  requestsHash?: Buffer
}
/** Information about the blob gas used in a block. */
export interface BlobGas {
  /**
   * The total amount of blob gas consumed by the transactions within the
   * block.
   */
  gasUsed: bigint
  /**
   * The running total of blob gas consumed in excess of the target, prior to
   * the block. Blocks with above-target blob gas consumption increase this
   * value, blocks with below-target blob gas consumption decrease it
   * (bounded at 0).
   */
  excessGas: bigint
}
/** The result of executing a call override. */
export interface CallOverrideResult {
  result: Buffer
  shouldRevert: boolean
}
/** Identifier for the Ethereum spec. */
export const enum SpecId {
  /** Frontier */
  Frontier = 0,
  /** Frontier Thawing */
  FrontierThawing = 1,
  /** Homestead */
  Homestead = 2,
  /** DAO Fork */
  DaoFork = 3,
  /** Tangerine */
  Tangerine = 4,
  /** Spurious Dragon */
  SpuriousDragon = 5,
  /** Byzantium */
  Byzantium = 6,
  /** Constantinople */
  Constantinople = 7,
  /** Petersburg */
  Petersburg = 8,
  /** Istanbul */
  Istanbul = 9,
  /** Muir Glacier */
  MuirGlacier = 10,
  /** Berlin */
  Berlin = 11,
  /** London */
  London = 12,
  /** Arrow Glacier */
  ArrowGlacier = 13,
  /** Gray Glacier */
  GrayGlacier = 14,
  /** Merge */
  Merge = 15,
  /** Shanghai */
  Shanghai = 16,
  /** Cancun */
  Cancun = 17,
  /** Prague */
  Prague = 18,
  /** Latest */
  Latest = 19
}
export interface DebugTraceResult {
  pass: boolean
  gasUsed: bigint
  output?: Buffer
  structLogs: Array<DebugTraceLogItem>
}
export interface DebugTraceLogItem {
  /** Program Counter */
  pc: bigint
  op: number
  /** Gas left before executing this operation as hex number. */
  gas: string
  /** Gas cost of this operation as hex number. */
  gasCost: string
  /** Array of all values (hex numbers) on the stack */
  stack?: Array<string>
  /** Depth of the call stack */
  depth: bigint
  /** Size of memory array */
  memSize: bigint
  /** Name of the operation */
  opName: string
  /** Description of an error as a hex string. */
  error?: string
  /** Array of all allocated values as hex strings. */
  memory?: Array<string>
  /** Map of all stored values with keys and values encoded as hex strings. */
  storage?: Record<string, string>
}
/** Ethereum execution log. */
export interface ExecutionLog {
  address: Buffer
  topics: Array<Buffer>
  data: Buffer
}
export interface ContractAndFunctionName {
  /** The contract name. */
  contractName: string
  /** The function name. Only present for calls. */
  functionName?: string
}
export interface LoggerConfig {
  /** Whether to enable the logger. */
  enable: boolean
  decodeConsoleLogInputsCallback: (inputs: Buffer[]) => string[]
  printLineCallback: (message: string, replace: boolean) => void
}
/** Configuration for a chain */
export interface ChainConfig {
  /** The chain ID */
  chainId: bigint
  /** The chain's supported hardforks */
  hardforks: Array<HardforkActivation>
}
/** Configuration for forking a blockchain */
export interface ForkConfig {
  /** The URL of the JSON-RPC endpoint to fork from */
  jsonRpcUrl: string
  /**
   * The block number to fork from. If not provided, the latest safe block is
   * used.
   */
  blockNumber?: bigint
  /** The HTTP headers to use when making requests to the JSON-RPC endpoint */
  httpHeaders?: Array<HttpHeader>
}
export interface HttpHeader {
  name: string
  value: string
}
/** Configuration for a hardfork activation */
export interface HardforkActivation {
  /** The block number at which the hardfork is activated */
  blockNumber: bigint
  /** The activated hardfork */
  specId: SpecId
}
/**The type of ordering to use when selecting blocks to mine. */
export const enum MineOrdering {
  /**Insertion order */
  Fifo = 'Fifo',
  /**Effective miner fee */
  Priority = 'Priority'
}
/** Configuration for the provider's mempool. */
export interface MemPoolConfig {
  order: MineOrdering
}
export interface IntervalRange {
  min: bigint
  max: bigint
}
/** Configuration for the provider's miner. */
export interface MiningConfig {
  autoMine: boolean
  interval?: bigint | IntervalRange
  memPool: MemPoolConfig
}
/** Configuration for a provider */
export interface ProviderConfig {
  /** Whether to allow blocks with the same timestamp */
  allowBlocksWithSameTimestamp: boolean
  /** Whether to allow unlimited contract size */
  allowUnlimitedContractSize: boolean
  /** Whether to return an `Err` when `eth_call` fails */
  bailOnCallFailure: boolean
  /** Whether to return an `Err` when a `eth_sendTransaction` fails */
  bailOnTransactionFailure: boolean
  /** The gas limit of each block */
  blockGasLimit: bigint
  /** The directory to cache remote JSON-RPC responses */
  cacheDir?: string
  /** The chain ID of the blockchain */
  chainId: bigint
  /** The configuration for chains */
  chains: Array<ChainConfig>
  /** The address of the coinbase */
  coinbase: Buffer
  /** Enables RIP-7212 */
  enableRip7212: boolean
  /**
   * The configuration for forking a blockchain. If not provided, a local
   * blockchain will be created
   */
  fork?: ForkConfig
  /** The genesis accounts of the blockchain */
  genesisAccounts: Array<GenesisAccount>
  /** The hardfork of the blockchain */
  hardfork: SpecId
  /**
   * The initial base fee per gas of the blockchain. Required for EIP-1559
   * transactions and later
   */
  initialBaseFeePerGas?: bigint
  /** The initial blob gas of the blockchain. Required for EIP-4844 */
  initialBlobGas?: BlobGas
  /** The initial date of the blockchain, in seconds since the Unix epoch */
  initialDate?: bigint
  /**
   * The initial parent beacon block root of the blockchain. Required for
   * EIP-4788
   */
  initialParentBeaconBlockRoot?: Buffer
  /** The minimum gas price of the next block. */
  minGasPrice: bigint
  /** The configuration for the miner */
  mining: MiningConfig
  /** The network ID of the blockchain */
  networkId: bigint
}
/** Tracing config for Solidity stack trace generation. */
export interface TracingConfigWithBuffers {
  /**
   * Build information to use for decoding contracts. Either a Hardhat v2
   * build info file that contains both input and output or a Hardhat v3
   * build info file that doesn't contain output and a separate output file.
   */
  buildInfos?: Array<Uint8Array> | Array<BuildInfoAndOutput>
  /** Whether to ignore contracts whose name starts with "Ignored". */
  ignoreContracts?: boolean
}
/**
 * Hardhat V3 build info where the compiler output is not part of the build
 * info file.
 */
export interface BuildInfoAndOutput {
  /** The build info input file */
  buildInfo: Uint8Array
  /** The build info output file */
  output: Uint8Array
}
/** The possible reasons for successful termination of the EVM. */
export const enum SuccessReason {
  /** The opcode `STOP` was called */
  Stop = 0,
  /** The opcode `RETURN` was called */
  Return = 1,
  /** The opcode `SELFDESTRUCT` was called */
  SelfDestruct = 2,
  EofReturnContract = 3
}
export interface CallOutput {
  /** Return value */
  returnValue: Buffer
}
export interface CreateOutput {
  /** Return value */
  returnValue: Buffer
  /** Optionally, a 160-bit address */
  address?: Buffer
}
/** The result when the EVM terminates successfully. */
export interface SuccessResult {
  /** The reason for termination */
  reason: SuccessReason
  /** The amount of gas used */
  gasUsed: bigint
  /** The amount of gas refunded */
  gasRefunded: bigint
  /** The logs */
  logs: Array<ExecutionLog>
  /** The transaction output */
  output: CallOutput | CreateOutput
}
/** The result when the EVM terminates due to a revert. */
export interface RevertResult {
  /** The amount of gas used */
  gasUsed: bigint
  /** The transaction output */
  output: Buffer
}
/**
 * Indicates that the EVM has experienced an exceptional halt. This causes
 * execution to immediately end with all gas being consumed.
 */
export const enum ExceptionalHalt {
  OutOfGas = 0,
  OpcodeNotFound = 1,
  InvalidFEOpcode = 2,
  InvalidJump = 3,
  NotActivated = 4,
  StackUnderflow = 5,
  StackOverflow = 6,
  OutOfOffset = 7,
  CreateCollision = 8,
  PrecompileError = 9,
  NonceOverflow = 10,
  /** Create init code size exceeds limit (runtime). */
  CreateContractSizeLimit = 11,
  /** Error on created contract that begins with EF */
  CreateContractStartingWithEF = 12,
  /** EIP-3860: Limit and meter initcode. Initcode size limit exceeded. */
  CreateInitCodeSizeLimit = 13,
  /** Aux data overflow, new aux data is larger tha u16 max size. */
  EofAuxDataOverflow = 14,
  /** Aud data is smaller then already present data size. */
  EofAuxDataTooSmall = 15,
  /** EOF Subroutine stack overflow */
  EOFFunctionStackOverflow = 16,
  /** Check for target address validity is only done inside subcall. */
  InvalidEXTCALLTarget = 17
}
/** The result when the EVM terminates due to an exceptional halt. */
export interface HaltResult {
  /** The exceptional halt that occurred */
  reason: ExceptionalHalt
  /**
   * Halting will spend all the gas and will thus be equal to the specified
   * gas limit
   */
  gasUsed: bigint
}
/** The result of executing a transaction. */
export interface ExecutionResult {
  /** The transaction result */
  result: SuccessResult | RevertResult | HaltResult
  /** Optional contract address if the transaction created a new contract. */
  contractAddress?: Buffer
}
/** A compilation artifact. */
export interface Artifact {
  /** The identifier of the artifact. */
  id: ArtifactId
  /** The test contract. */
  contract: ContractData
}
/** The identifier of a Solidity contract. */
export interface ArtifactId {
  /** The name of the contract. */
  name: string
  /** Original source file path. */
  source: string
  /** The solc semver string. */
  solcVersion: string
}
/** A test contract to execute. */
export interface ContractData {
  /** Contract ABI as json string. */
  abi: string
  /**
   * Contract creation code as hex string. It can be missing if the contract
   * is ABI only.
   */
  bytecode?: string
  /** The link references of the deployment bytecode. */
  linkReferences?: Record<string, Record<string, Array<LinkReference>>>
  /**
   * Contract runtime code as hex string. It can be missing if the contract
   * is ABI only.
   */
  deployedBytecode?: string
  /** The link references of the deployed bytecode. */
  deployedLinkReferences?: Record<string, Record<string, Array<LinkReference>>>
}
export interface LinkReference {
  start: number
  length: number
}
/**
 * Solidity test runner configuration arguments exposed through the ffi.
 * Docs based on https://book.getfoundry.sh/reference/config/testing
 */
export interface SolidityTestRunnerConfigArgs {
  /**
   * The absolute path to the project root directory.
   * Relative paths in cheat codes are resolved against this path.
   */
  projectRoot: string
  /** Configures the permissions of cheat codes that access the file system. */
  fsPermissions?: Array<PathPermission>
  /** Whether to support the `testFail` prefix. Defaults to false. */
  testFail?: boolean
  /** Address labels for traces. Defaults to none. */
  labels?: Array<AddressLabel>
  /**
   * Whether to enable isolation of calls. In isolation mode all top-level
   * calls are executed as a separate transaction in a separate EVM
   * context, enabling more precise gas accounting and transaction state
   * changes.
   * Defaults to false.
   */
  isolate?: boolean
  /**
   * Whether or not to enable the ffi cheatcode.
   * Warning: Enabling this cheatcode has security implications, as it allows
   * tests to execute arbitrary programs on your computer.
   * Defaults to false.
   */
  ffi?: boolean
  /**
   * The value of `msg.sender` in tests as hex string.
   * Defaults to `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`.
   */
  sender?: Buffer
  /**
   * The value of `tx.origin` in tests as hex string.
   * Defaults to `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`.
   */
  txOrigin?: Buffer
  /**
   * The initial balance of the sender in tests.
   * Defaults to `0xffffffffffffffffffffffff`.
   */
  initialBalance?: bigint
  /**
   * The value of `block.number` in tests.
   * Defaults to `1`.
   */
  blockNumber?: bigint
  /**
   * The value of the `chainid` opcode in tests.
   * Defaults to `31337`.
   */
  chainId?: bigint
  /**
   * The gas limit for each test case.
   * Defaults to `9_223_372_036_854_775_807` (`i64::MAX`).
   */
  gasLimit?: bigint
  /**
   * The price of gas (in wei) in tests.
   * Defaults to `0`.
   */
  gasPrice?: bigint
  /**
   * The base fee per gas (in wei) in tests.
   * Defaults to `0`.
   */
  blockBaseFeePerGas?: bigint
  /**
   * The value of `block.coinbase` in tests.
   * Defaults to `0x0000000000000000000000000000000000000000`.
   */
  blockCoinbase?: Buffer
  /**
   * The value of `block.timestamp` in tests.
   * Defaults to 1.
   */
  blockTimestamp?: bigint
  /**
   * The value of `block.difficulty` in tests.
   * Defaults to 0.
   */
  blockDifficulty?: bigint
  /**
   * The `block.gaslimit` value during EVM execution.
   * Defaults to none.
   */
  blockGasLimit?: bigint
  /**
   * Whether to disable the block gas limit.
   * Defaults to false.
   */
  disableBlockGasLimit?: boolean
  /**
   * The memory limit of the EVM in bytes.
   * Defaults to 33_554_432 (2^25 = 32MiB).
   */
  memoryLimit?: bigint
  /**
   * If set, all tests are run in fork mode using this url or remote name.
   * Defaults to none.
   */
  ethRpcUrl?: string
  /** Pins the block number for the global state fork. */
  forkBlockNumber?: bigint
  /**
   * Map of RPC endpoints from chain name to RPC urls for fork cheat codes,
   * e.g. `{ "optimism": "https://optimism.alchemyapi.io/v2/..." }`
   */
  rpcEndpoints?: Record<string, string>
  /**
   * Optional RPC cache path. If this is none, then no RPC calls will be
   * cached, otherwise data is cached to `<rpc_cache_path>/<chain
   * id>/<block number>`. Caching can be disabled for specific chains
   * with `rpc_storage_caching`.
   */
  rpcCachePath?: string
  /** What RPC endpoints are cached. Defaults to all. */
  rpcStorageCaching?: StorageCachingConfig
  /**
   * The number of seconds to wait before `vm.prompt` reverts with a timeout.
   * Defaults to 120.
   */
  promptTimeout?: number
  /** Fuzz testing configuration. */
  fuzz?: FuzzConfigArgs
  /**
   * Invariant testing configuration.
   * If an invariant config setting is not set, but a corresponding fuzz
   * config value is set, then the fuzz config value will be used.
   */
  invariant?: InvariantConfigArgs
}
/** Fuzz testing configuration */
export interface FuzzConfigArgs {
  /** Path where fuzz failures are recorded and replayed if set. */
  failurePersistDir?: string
  /** Name of the file to record fuzz failures, defaults to `failures`. */
  failurePersistFile?: string
  /**
   * The amount of fuzz runs to perform for each fuzz test case. Higher
   * values gives more confidence in results at the cost of testing
   * speed.
   * Defaults to 256.
   */
  runs?: number
  /**
   * The maximum number of combined inputs that may be rejected before the
   * test as a whole aborts. “Global” filters apply to the whole test
   * case. If the test case is rejected, the whole thing is regenerated.
   * Defaults to 65536.
   */
  maxTestRejects?: number
  /**
   * Hexadecimal string.
   * Optional seed for the fuzzing RNG algorithm.
   * Defaults to None.
   */
  seed?: string
  /**
   * Integer between 0 and 100.
   * The weight of the dictionary. A higher dictionary weight will bias the
   * fuzz inputs towards “interesting” values, e.g. boundary values like
   * type(uint256).max or contract addresses from your environment.
   * Defaults to 40.
   */
  dictionaryWeight?: number
  /**
   * The flag indicating whether to include values from storage.
   * Defaults to true.
   */
  includeStorage?: boolean
  /**
   * The flag indicating whether to include push bytes values.
   * Defaults to true.
   */
  includePushBytes?: boolean
}
/** Invariant testing configuration. */
export interface InvariantConfigArgs {
  /** Path where invariant failures are recorded and replayed if set. */
  failurePersistDir?: string
  /**
   * The number of runs that must execute for each invariant test group.
   * Defaults to 256.
   */
  runs?: number
  /**
   * The number of calls executed to attempt to break invariants in one run.
   * Defaults to 500.
   */
  depth?: number
  /**
   * Fails the invariant fuzzing if a revert occurs.
   * Defaults to false.
   */
  failOnRevert?: boolean
  /**
   * Overrides unsafe external calls when running invariant tests, useful for
   * e.g. performing reentrancy checks.
   * Defaults to false.
   */
  callOverride?: boolean
  /**
   * Integer between 0 and 100.
   * The weight of the dictionary. A higher dictionary weight will bias the
   * fuzz inputs towards “interesting” values, e.g. boundary values like
   * type(uint256).max or contract addresses from your environment.
   * Defaults to 40.
   */
  dictionaryWeight?: number
  /**
   * The flag indicating whether to include values from storage.
   * Defaults to true.
   */
  includeStorage?: boolean
  /**
   * The flag indicating whether to include push bytes values.
   * Defaults to true.
   */
  includePushBytes?: boolean
  /**
   * The maximum number of attempts to shrink a failed the sequence. Shrink
   * process is disabled if set to 0.
   * Defaults to 5000.
   */
  shrinkRunLimit?: number
}
/** Settings to configure caching of remote */
export interface StorageCachingConfig {
  /**
   * Chains to cache. Either all or none or a list of chain names, e.g.
   * ["optimism", "mainnet"].
   */
  chains: CachedChains | Array<string>
  /** Endpoints to cache. Either all or remote or a regex. */
  endpoints: CachedEndpoints | string
}
/** What chains to cache */
export const enum CachedChains {
  /** Cache all chains */
  All = 0,
  /** Don't cache anything */
  None = 1
}
/** What endpoints to enable caching for */
export const enum CachedEndpoints {
  /** Cache all endpoints */
  All = 0,
  /** Only cache non-local host endpoints */
  Remote = 1
}
/** Represents an access permission to a single path */
export interface PathPermission {
  /** Permission level to access the `path` */
  access: FsAccessPermission
  /** The targeted path guarded by the permission */
  path: string
}
/** Determines the status of file system access */
export const enum FsAccessPermission {
  /** FS access is allowed with `read` + `write` permission */
  ReadWrite = 0,
  /** Only reading is allowed */
  Read = 1,
  /** Only writing is allowed */
  Write = 2
}
export interface AddressLabel {
  /** The address to label */
  address: Buffer
  /** The label to assign to the address */
  label: string
}
/** The stack trace result */
export interface StackTrace {
  /** Enum tag for JS. */
  kind: "StackTrace"
  /** The stack trace entries */
  entries: Array<SolidityStackTraceEntry>
}
/** We couldn't generate stack traces, because an unexpected error occurred. */
export interface UnexpectedError {
  /** Enum tag for JS. */
  kind: "UnexpectedError"
  /** The error message from the unexpected error. */
  errorMessage: string
}
/**
 * We couldn't generate stack traces, because the stack trace generation
 * heuristics failed due to an unknown reason.
 */
export interface HeuristicFailed {
  /** Enum tag for JS. */
  kind: "HeuristicFailed"
}
/**
 * We couldn't generate stack traces, because the test execution is unsafe to
 * replay due to indeterminism. This can be caused by either specifying a fork
 * url without a fork block number in the test runner config or using impure
 * cheatcodes.
 */
export interface UnsafeToReplay {
  /** Enum tag for JS. */
  kind: "UnsafeToReplay"
  /**
   * Indeterminism due to specifying a fork url without a fork block number
   * in the test runner config.
   */
  globalForkLatest: boolean
  /**
   * The list of executed impure cheatcode signatures. We collect function
   * signatures instead of function names as whether a cheatcode is impure
   * can depend on the arguments it takes (e.g. `createFork` without a second
   * argument means implicitly fork from “latest”). Example signature:
   * `function createSelectFork(string calldata urlOrAlias) external returns
   * (uint256 forkId);`.
   */
  impureCheatcodes: Array<string>
}
/**The result of a test execution. */
export const enum TestStatus {
  /**Test success */
  Success = 'Success',
  /**Test failure */
  Failure = 'Failure',
  /**Test skipped */
  Skipped = 'Skipped'
}
/** See [edr_solidity_tests::result::TestKind::Standard] */
export interface StandardTestKind {
  /** The gas consumed by the test. */
  readonly consumedGas: bigint
}
/** See [edr_solidity_tests::result::TestKind::Fuzz] */
export interface FuzzTestKind {
  /** See [edr_solidity_tests::result::TestKind::Fuzz] */
  readonly runs: bigint
  /** See [edr_solidity_tests::result::TestKind::Fuzz] */
  readonly meanGas: bigint
  /** See [edr_solidity_tests::result::TestKind::Fuzz] */
  readonly medianGas: bigint
}
/** See [edr_solidity_tests::fuzz::FuzzCase] */
export interface FuzzCase {
  /** The calldata used for this fuzz test */
  readonly calldata: Buffer
  /** Consumed gas */
  readonly gas: bigint
  /** The initial gas stipend for the transaction */
  readonly stipend: bigint
}
/** See [edr_solidity_tests::result::TestKind::Invariant] */
export interface InvariantTestKind {
  /** See [edr_solidity_tests::result::TestKind::Invariant] */
  readonly runs: bigint
  /** See [edr_solidity_tests::result::TestKind::Invariant] */
  readonly calls: bigint
  /** See [edr_solidity_tests::result::TestKind::Invariant] */
  readonly reverts: bigint
}
/**
 * Original sequence size and sequence of calls used as a counter example
 * for invariant tests.
 */
export interface CounterExampleSequence {
  /** The original sequence size before shrinking. */
  originalSequenceSize: bigint
  /** The shrunk counterexample sequence. */
  sequence: Array<BaseCounterExample>
}
/** See [edr_solidity_tests::fuzz::BaseCounterExample] */
export interface BaseCounterExample {
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::sender] */
  readonly sender?: Buffer
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::addr] */
  readonly address?: Buffer
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::calldata] */
  readonly calldata: Buffer
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::contract_name] */
  readonly contractName?: string
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::signature] */
  readonly signature?: string
  /** See [edr_solidity_tests::fuzz::BaseCounterExample::args] */
  readonly args?: string
}
/**
 * Executes Solidity tests.
 *
 * The function will return as soon as test execution is started.
 * The progress callback will be called with the results of each test suite.
 * It is up to the caller to track how many times the callback is called to
 * know when all tests are done.
 * The error callback is called if an invalid configuration value is provided.
 */
export declare function runSolidityTests(artifacts: Array<Artifact>, testSuites: Array<ArtifactId>, configArgs: SolidityTestRunnerConfigArgs, tracingConfig: TracingConfigWithBuffers, progressCallback: (result: SuiteResult) => void, errorCallback: (error: Error) => void): void
export interface SubscriptionEvent {
  filterId: bigint
  result: any
}
export declare function linkHexStringBytecode(code: string, address: string, position: number): string
export declare function printStackTrace(trace: SolidityStackTrace): void
/** Represents the exit code of the EVM. */
export const enum ExitCode {
  /** Execution was successful. */
  SUCCESS = 0,
  /** Execution was reverted. */
  REVERT = 1,
  /** Execution ran out of gas. */
  OUT_OF_GAS = 2,
  /** Execution encountered an internal error. */
  INTERNAL_ERROR = 3,
  /** Execution encountered an invalid opcode. */
  INVALID_OPCODE = 4,
  /** Execution encountered a stack underflow. */
  STACK_UNDERFLOW = 5,
  /** Create init code size exceeds limit (runtime). */
  CODESIZE_EXCEEDS_MAXIMUM = 6,
  /** Create collision. */
  CREATE_COLLISION = 7,
  /** Unknown halt reason. */
  UNKNOWN_HALT_REASON = 8
}
export const enum ContractFunctionType {
  CONSTRUCTOR = 0,
  FUNCTION = 1,
  FALLBACK = 2,
  RECEIVE = 3,
  GETTER = 4,
  MODIFIER = 5,
  FREE_FUNCTION = 6
}
export const enum StackTraceEntryType {
  CALLSTACK_ENTRY = 0,
  UNRECOGNIZED_CREATE_CALLSTACK_ENTRY = 1,
  UNRECOGNIZED_CONTRACT_CALLSTACK_ENTRY = 2,
  PRECOMPILE_ERROR = 3,
  REVERT_ERROR = 4,
  PANIC_ERROR = 5,
  CUSTOM_ERROR = 6,
  FUNCTION_NOT_PAYABLE_ERROR = 7,
  INVALID_PARAMS_ERROR = 8,
  FALLBACK_NOT_PAYABLE_ERROR = 9,
  FALLBACK_NOT_PAYABLE_AND_NO_RECEIVE_ERROR = 10,
  UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR = 11,
  MISSING_FALLBACK_OR_RECEIVE_ERROR = 12,
  RETURNDATA_SIZE_ERROR = 13,
  NONCONTRACT_ACCOUNT_CALLED_ERROR = 14,
  CALL_FAILED_ERROR = 15,
  DIRECT_LIBRARY_CALL_ERROR = 16,
  UNRECOGNIZED_CREATE_ERROR = 17,
  UNRECOGNIZED_CONTRACT_ERROR = 18,
  OTHER_EXECUTION_ERROR = 19,
  UNMAPPED_SOLC_0_6_3_REVERT_ERROR = 20,
  CONTRACT_TOO_LARGE_ERROR = 21,
  INTERNAL_FUNCTION_CALLSTACK_ENTRY = 22,
  CONTRACT_CALL_RUN_OUT_OF_GAS_ERROR = 23
}
export declare function stackTraceEntryTypeToString(val: StackTraceEntryType): string
export const FALLBACK_FUNCTION_NAME: string
export const RECEIVE_FUNCTION_NAME: string
export const CONSTRUCTOR_FUNCTION_NAME: string
export const UNRECOGNIZED_FUNCTION_NAME: string
export const UNKNOWN_FUNCTION_NAME: string
export const PRECOMPILE_FUNCTION_NAME: string
export const UNRECOGNIZED_CONTRACT_NAME: string
export interface SourceReference {
  sourceName: string
  sourceContent: string
  contract?: string
  function?: string
  line: number
  range: Array<number>
}
export interface CallstackEntryStackTraceEntry {
  type: StackTraceEntryType.CALLSTACK_ENTRY
  sourceReference: SourceReference
  functionType: ContractFunctionType
}
export interface UnrecognizedCreateCallstackEntryStackTraceEntry {
  type: StackTraceEntryType.UNRECOGNIZED_CREATE_CALLSTACK_ENTRY
  sourceReference?: undefined
}
export interface UnrecognizedContractCallstackEntryStackTraceEntry {
  type: StackTraceEntryType.UNRECOGNIZED_CONTRACT_CALLSTACK_ENTRY
  address: Uint8Array
  sourceReference?: undefined
}
export interface PrecompileErrorStackTraceEntry {
  type: StackTraceEntryType.PRECOMPILE_ERROR
  precompile: number
  sourceReference?: undefined
}
export interface RevertErrorStackTraceEntry {
  type: StackTraceEntryType.REVERT_ERROR
  returnData: Uint8Array
  sourceReference: SourceReference
  isInvalidOpcodeError: boolean
}
export interface PanicErrorStackTraceEntry {
  type: StackTraceEntryType.PANIC_ERROR
  errorCode: bigint
  sourceReference?: SourceReference
}
export interface CustomErrorStackTraceEntry {
  type: StackTraceEntryType.CUSTOM_ERROR
  message: string
  sourceReference: SourceReference
}
export interface FunctionNotPayableErrorStackTraceEntry {
  type: StackTraceEntryType.FUNCTION_NOT_PAYABLE_ERROR
  value: bigint
  sourceReference: SourceReference
}
export interface InvalidParamsErrorStackTraceEntry {
  type: StackTraceEntryType.INVALID_PARAMS_ERROR
  sourceReference: SourceReference
}
export interface FallbackNotPayableErrorStackTraceEntry {
  type: StackTraceEntryType.FALLBACK_NOT_PAYABLE_ERROR
  value: bigint
  sourceReference: SourceReference
}
export interface FallbackNotPayableAndNoReceiveErrorStackTraceEntry {
  type: StackTraceEntryType.FALLBACK_NOT_PAYABLE_AND_NO_RECEIVE_ERROR
  value: bigint
  sourceReference: SourceReference
}
export interface UnrecognizedFunctionWithoutFallbackErrorStackTraceEntry {
  type: StackTraceEntryType.UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR
  sourceReference: SourceReference
}
export interface MissingFallbackOrReceiveErrorStackTraceEntry {
  type: StackTraceEntryType.MISSING_FALLBACK_OR_RECEIVE_ERROR
  sourceReference: SourceReference
}
export interface ReturndataSizeErrorStackTraceEntry {
  type: StackTraceEntryType.RETURNDATA_SIZE_ERROR
  sourceReference: SourceReference
}
export interface NonContractAccountCalledErrorStackTraceEntry {
  type: StackTraceEntryType.NONCONTRACT_ACCOUNT_CALLED_ERROR
  sourceReference: SourceReference
}
export interface CallFailedErrorStackTraceEntry {
  type: StackTraceEntryType.CALL_FAILED_ERROR
  sourceReference: SourceReference
}
export interface DirectLibraryCallErrorStackTraceEntry {
  type: StackTraceEntryType.DIRECT_LIBRARY_CALL_ERROR
  sourceReference: SourceReference
}
export interface UnrecognizedCreateErrorStackTraceEntry {
  type: StackTraceEntryType.UNRECOGNIZED_CREATE_ERROR
  returnData: Uint8Array
  sourceReference?: undefined
  isInvalidOpcodeError: boolean
}
export interface UnrecognizedContractErrorStackTraceEntry {
  type: StackTraceEntryType.UNRECOGNIZED_CONTRACT_ERROR
  address: Uint8Array
  returnData: Uint8Array
  sourceReference?: undefined
  isInvalidOpcodeError: boolean
}
export interface OtherExecutionErrorStackTraceEntry {
  type: StackTraceEntryType.OTHER_EXECUTION_ERROR
  sourceReference?: SourceReference
}
export interface UnmappedSolc063RevertErrorStackTraceEntry {
  type: StackTraceEntryType.UNMAPPED_SOLC_0_6_3_REVERT_ERROR
  sourceReference?: SourceReference
}
export interface ContractTooLargeErrorStackTraceEntry {
  type: StackTraceEntryType.CONTRACT_TOO_LARGE_ERROR
  sourceReference?: SourceReference
}
export interface InternalFunctionCallStackEntry {
  type: StackTraceEntryType.INTERNAL_FUNCTION_CALLSTACK_ENTRY
  pc: number
  sourceReference: SourceReference
}
export interface ContractCallRunOutOfGasError {
  type: StackTraceEntryType.CONTRACT_CALL_RUN_OUT_OF_GAS_ERROR
  sourceReference?: SourceReference
}
export interface TracingMessage {
  /** Sender address */
  readonly caller: Buffer
  /** Recipient address. None if it is a Create message. */
  readonly to?: Buffer
  /** Whether it's a static call */
  readonly isStaticCall: boolean
  /** Transaction gas limit */
  readonly gasLimit: bigint
  /** Depth of the message */
  readonly depth: number
  /** Input data of the message */
  readonly data: Buffer
  /** Value sent in the message */
  readonly value: bigint
  /**
   * Address of the code that is being executed. Can be different from `to`
   * if a delegate call is being done.
   */
  readonly codeAddress?: Buffer
  /** Code of the contract that is being executed. */
  readonly code?: Buffer
}
export interface TracingStep {
  /** Call depth */
  readonly depth: number
  /** The program counter */
  readonly pc: bigint
  /** The executed op code */
  readonly opcode: string
  /**
   * The entries on the stack. It only contains the top element unless
   * verbose tracing is enabled. The vector is empty if there are no elements
   * on the stack.
   */
  readonly stack: Array<bigint>
  /** The memory at the step. None if verbose tracing is disabled. */
  readonly memory?: Buffer
}
export interface TracingMessageResult {
  /** Execution result */
  readonly executionResult: ExecutionResult
}
/**
 * Returns the latest version of solc that EDR officially
 * supports and is tested against.
 */
export declare function getLatestSupportedSolcVersion(): string
export interface Withdrawal {
  /** The index of withdrawal */
  index: bigint
  /** The index of the validator that generated the withdrawal */
  validatorIndex: bigint
  /** The recipient address for withdrawal value */
  address: Buffer
  /** The value contained in withdrawal */
  amount: bigint
}
export declare class EdrContext {
  /**Creates a new [`EdrContext`] instance. Should only be called once! */
  constructor()
}
/** A JSON-RPC provider for Ethereum. */
export declare class Provider {
  /**Constructs a new provider with the provided configuration. */
  static withConfig(context: EdrContext, config: ProviderConfig, loggerConfig: LoggerConfig, tracingConfig: TracingConfigWithBuffers, subscriberCallback: (event: SubscriptionEvent) => void): Promise<Provider>
  /**Handles a JSON-RPC request and returns a JSON-RPC response. */
  handleRequest(jsonRequest: string): Promise<Response>
  setCallOverrideCallback(callOverrideCallback: (contract_address: Buffer, data: Buffer) => Promise<CallOverrideResult | undefined>): void
  /**
   * Set to `true` to make the traces returned with `eth_call`,
   * `eth_estimateGas`, `eth_sendRawTransaction`, `eth_sendTransaction`,
   * `evm_mine`, `hardhat_mine` include the full stack and memory. Set to
   * `false` to disable this.
   */
  setVerboseTracing(verboseTracing: boolean): void
}
export declare class Response {
  /** Returns the response data as a JSON string or a JSON object. */
  get data(): string | any
  get traces(): Array<RawTrace>
  /**Compute the error stack trace. Return the stack trace if it can be decoded, otherwise returns none. Throws if there was an error computing the stack trace. */
  stackTrace(): SolidityStackTrace | null
}
/** See [edr_solidity_tests::result::SuiteResult] */
export declare class SuiteResult {
  /**
   * The artifact id can be used to match input to result in the progress
   * callback
   */
  readonly id: ArtifactId
  /** See [edr_solidity_tests::result::SuiteResult::duration] */
  readonly durationMs: bigint
  /** See [edr_solidity_tests::result::SuiteResult::test_results] */
  readonly testResults: Array<TestResult>
  /** See [edr_solidity_tests::result::SuiteResult::warnings] */
  readonly warnings: Array<string>
}
/** See [edr_solidity_tests::result::TestResult] */
export declare class TestResult {
  /** The name of the test. */
  readonly name: string
  /** See [edr_solidity_tests::result::TestResult::status] */
  readonly status: TestStatus
  /** See [edr_solidity_tests::result::TestResult::reason] */
  readonly reason?: string
  /** See [edr_solidity_tests::result::TestResult::counterexample] */
  readonly counterexample?: BaseCounterExample | CounterExampleSequence
  /** See [edr_solidity_tests::result::TestResult::decoded_logs] */
  readonly decodedLogs: Array<string>
  /** See [edr_solidity_tests::result::TestResult::kind] */
  readonly kind: StandardTestKind | FuzzTestKind | InvariantTestKind
  /** See [edr_solidity_tests::result::TestResult::duration] */
  readonly durationMs: bigint
  /**
   * Compute the error stack trace.
   * The result is either the stack trace or the reason why we couldn't
   * generate the stack trace.
   * Returns null if the test status is succeeded or skipped.
   * Cannot throw.
   */
  stackTrace(): StackTrace | UnexpectedError | HeuristicFailed | UnsafeToReplay | null
}
export declare class Exit {
  get kind(): ExitCode
  isError(): boolean
  getReason(): string
}
/**
 * Opaque handle to the `Bytecode` struct.
 * Only used on the JS side by the `VmTraceDecoder` class.
 */
export declare class BytecodeWrapper { }
export declare class ReturnData {
  readonly value: Uint8Array
  constructor(value: Uint8Array)
  isEmpty(): boolean
  isErrorReturnData(): boolean
  isPanicReturnData(): boolean
  decodeError(): string
  decodePanic(): bigint
}
export declare class RawTrace {
  trace(): Array<TracingMessage | TracingStep | TracingMessageResult>
}
