// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./edr.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-android-arm64')
        const bindingPackageVersion = require('@nomicfoundation/edr-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./edr.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-android-arm-eabi')
        const bindingPackageVersion = require('@nomicfoundation/edr-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./edr.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-win32-x64-gnu')
        const bindingPackageVersion = require('@nomicfoundation/edr-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./edr.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-win32-x64-msvc')
        const bindingPackageVersion = require('@nomicfoundation/edr-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./edr.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-win32-ia32-msvc')
        const bindingPackageVersion = require('@nomicfoundation/edr-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./edr.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-win32-arm64-msvc')
        const bindingPackageVersion = require('@nomicfoundation/edr-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./edr.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@nomicfoundation/edr-darwin-universal')
      const bindingPackageVersion = require('@nomicfoundation/edr-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./edr.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-darwin-x64')
        const bindingPackageVersion = require('@nomicfoundation/edr-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./edr.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-darwin-arm64')
        const bindingPackageVersion = require('@nomicfoundation/edr-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./edr.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-freebsd-x64')
        const bindingPackageVersion = require('@nomicfoundation/edr-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./edr.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-freebsd-arm64')
        const bindingPackageVersion = require('@nomicfoundation/edr-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./edr.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-x64-musl')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./edr.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-x64-gnu')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./edr.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-arm64-musl')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./edr.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-arm64-gnu')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./edr.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-arm-musleabihf')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./edr.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./edr.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-loong64-musl')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./edr.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-loong64-gnu')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./edr.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-riscv64-musl')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./edr.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@nomicfoundation/edr-linux-riscv64-gnu')
          const bindingPackageVersion = require('@nomicfoundation/edr-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./edr.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-linux-ppc64-gnu')
        const bindingPackageVersion = require('@nomicfoundation/edr-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./edr.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-linux-s390x-gnu')
        const bindingPackageVersion = require('@nomicfoundation/edr-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./edr.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-openharmony-arm64')
        const bindingPackageVersion = require('@nomicfoundation/edr-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./edr.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-openharmony-x64')
        const bindingPackageVersion = require('@nomicfoundation/edr-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./edr.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@nomicfoundation/edr-openharmony-arm')
        const bindingPackageVersion = require('@nomicfoundation/edr-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.12.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.12.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./edr.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('@nomicfoundation/edr-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.BytecodeWrapper = nativeBinding.BytecodeWrapper
module.exports.ContractDecoder = nativeBinding.ContractDecoder
module.exports.EdrContext = nativeBinding.EdrContext
module.exports.Exit = nativeBinding.Exit
module.exports.Precompile = nativeBinding.Precompile
module.exports.Provider = nativeBinding.Provider
module.exports.ProviderFactory = nativeBinding.ProviderFactory
module.exports.RawTrace = nativeBinding.RawTrace
module.exports.Response = nativeBinding.Response
module.exports.ReturnData = nativeBinding.ReturnData
module.exports.SolidityTestRunnerFactory = nativeBinding.SolidityTestRunnerFactory
module.exports.TestResult = nativeBinding.TestResult
module.exports.addStatementCoverageInstrumentation = nativeBinding.addStatementCoverageInstrumentation
module.exports.ARROW_GLACIER = nativeBinding.ARROW_GLACIER
module.exports.BEDROCK = nativeBinding.BEDROCK
module.exports.BERLIN = nativeBinding.BERLIN
module.exports.BYZANTIUM = nativeBinding.BYZANTIUM
module.exports.CachedChains = nativeBinding.CachedChains
module.exports.CachedEndpoints = nativeBinding.CachedEndpoints
module.exports.CallKind = nativeBinding.CallKind
module.exports.CANCUN = nativeBinding.CANCUN
module.exports.CANYON = nativeBinding.CANYON
module.exports.CheatcodeErrorCode = nativeBinding.CheatcodeErrorCode
module.exports.CollectStackTraces = nativeBinding.CollectStackTraces
module.exports.CONSTANTINOPLE = nativeBinding.CONSTANTINOPLE
module.exports.CONSTRUCTOR_FUNCTION_NAME = nativeBinding.CONSTRUCTOR_FUNCTION_NAME
module.exports.ContractFunctionType = nativeBinding.ContractFunctionType
module.exports.COVERAGE_LIBRARY_FILE_NAME = nativeBinding.COVERAGE_LIBRARY_FILE_NAME
module.exports.DAO_FORK = nativeBinding.DAO_FORK
module.exports.ECOTONE = nativeBinding.ECOTONE
module.exports.ExceptionalHalt = nativeBinding.ExceptionalHalt
module.exports.ExitCode = nativeBinding.ExitCode
module.exports.FALLBACK_FUNCTION_NAME = nativeBinding.FALLBACK_FUNCTION_NAME
module.exports.FJORD = nativeBinding.FJORD
module.exports.FRONTIER = nativeBinding.FRONTIER
module.exports.FRONTIER_THAWING = nativeBinding.FRONTIER_THAWING
module.exports.FsAccessPermission = nativeBinding.FsAccessPermission
module.exports.GasReportExecutionStatus = nativeBinding.GasReportExecutionStatus
module.exports.GENERIC_CHAIN_TYPE = nativeBinding.GENERIC_CHAIN_TYPE
module.exports.genericChainProviderFactory = nativeBinding.genericChainProviderFactory
module.exports.GRANITE = nativeBinding.GRANITE
module.exports.GRAY_GLACIER = nativeBinding.GRAY_GLACIER
module.exports.HOLOCENE = nativeBinding.HOLOCENE
module.exports.HOMESTEAD = nativeBinding.HOMESTEAD
module.exports.IncludeTraces = nativeBinding.IncludeTraces
module.exports.ISTANBUL = nativeBinding.ISTANBUL
module.exports.ISTHMUS = nativeBinding.ISTHMUS
module.exports.L1_CHAIN_TYPE = nativeBinding.L1_CHAIN_TYPE
module.exports.l1GenesisState = nativeBinding.l1GenesisState
module.exports.l1HardforkFromString = nativeBinding.l1HardforkFromString
module.exports.l1HardforkLatest = nativeBinding.l1HardforkLatest
module.exports.l1HardforkToString = nativeBinding.l1HardforkToString
module.exports.l1ProviderFactory = nativeBinding.l1ProviderFactory
module.exports.l1SolidityTestRunnerFactory = nativeBinding.l1SolidityTestRunnerFactory
module.exports.latestSupportedSolidityVersion = nativeBinding.latestSupportedSolidityVersion
module.exports.linkHexStringBytecode = nativeBinding.linkHexStringBytecode
module.exports.LogKind = nativeBinding.LogKind
module.exports.LONDON = nativeBinding.LONDON
module.exports.MERGE = nativeBinding.MERGE
module.exports.MineOrdering = nativeBinding.MineOrdering
module.exports.MUIR_GLACIER = nativeBinding.MUIR_GLACIER
module.exports.OP_CHAIN_TYPE = nativeBinding.OP_CHAIN_TYPE
module.exports.opGenesisState = nativeBinding.opGenesisState
module.exports.OpHardfork = nativeBinding.OpHardfork
module.exports.opHardforkFromString = nativeBinding.opHardforkFromString
module.exports.opHardforkToString = nativeBinding.opHardforkToString
module.exports.opLatestHardfork = nativeBinding.opLatestHardfork
module.exports.opProviderFactory = nativeBinding.opProviderFactory
module.exports.opSolidityTestRunnerFactory = nativeBinding.opSolidityTestRunnerFactory
module.exports.OSAKA = nativeBinding.OSAKA
module.exports.PETERSBURG = nativeBinding.PETERSBURG
module.exports.PRAGUE = nativeBinding.PRAGUE
module.exports.PRECOMPILE_FUNCTION_NAME = nativeBinding.PRECOMPILE_FUNCTION_NAME
module.exports.precompileP256Verify = nativeBinding.precompileP256Verify
module.exports.printStackTrace = nativeBinding.printStackTrace
module.exports.RECEIVE_FUNCTION_NAME = nativeBinding.RECEIVE_FUNCTION_NAME
module.exports.REGOLITH = nativeBinding.REGOLITH
module.exports.SHANGHAI = nativeBinding.SHANGHAI
module.exports.SpecId = nativeBinding.SpecId
module.exports.SPURIOUS_DRAGON = nativeBinding.SPURIOUS_DRAGON
module.exports.StackTraceEntryType = nativeBinding.StackTraceEntryType
module.exports.stackTraceEntryTypeToString = nativeBinding.stackTraceEntryTypeToString
module.exports.SuccessReason = nativeBinding.SuccessReason
module.exports.TANGERINE = nativeBinding.TANGERINE
module.exports.TestStatus = nativeBinding.TestStatus
module.exports.UNKNOWN_FUNCTION_NAME = nativeBinding.UNKNOWN_FUNCTION_NAME
module.exports.UNRECOGNIZED_CONTRACT_NAME = nativeBinding.UNRECOGNIZED_CONTRACT_NAME
module.exports.UNRECOGNIZED_FUNCTION_NAME = nativeBinding.UNRECOGNIZED_FUNCTION_NAME
