[package]
name = "edr_receipt_spec"
version.workspace = true
edition.workspace = true

[dependencies]
edr_chain_spec.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_rpc_spec.workspace = true

[lints]
workspace = true
