[package]
name = "foundry-evm-fuzz"
description = "EVM fuzzing implementation using `proptest`"

version.workspace = true
edition.workspace = true

[dependencies]
edr_common.workspace = true
edr_solidity.workspace = true
foundry-evm-core.workspace = true
foundry-evm-coverage.workspace = true
foundry-evm-traces.workspace = true

alloy-dyn-abi = { workspace = true, features = ["arbitrary", "eip712"] }
alloy-json-abi.workspace = true
alloy-primitives = { workspace = true, features = ["serde", "getrandom", "arbitrary", "rlp"] }
revm = { workspace = true, features = [
    "std",
    "serde",
    "memory_limit",
    "optional_eip3607",
    "optional_block_gas_limit",
    "optional_no_base_fee",
    "arbitrary",
] }

ciborium.workspace = true
eyre = "0.6"
itertools.workspace = true
parking_lot.workspace = true
proptest.workspace = true
rand.workspace = true
serde.workspace = true
thiserror = "1"
tracing = "0.1"
indexmap.workspace = true

[lints]
workspace = true
