name: Setup rust
description: Sets up rust

runs:
  using: composite
  steps:
    - name: Install Rust (stable)
      uses: ./.github/actions/setup-rust-toolchain
      with:
        toolchain: stable
        override: true

    - uses: Swatinem/rust-cache@v2
