name: Setup Rust
description: Sets up Rust

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
        cache: true
        # Do not override the RUSTFLAGS by default and instead do that per job,
        # if needed. Setting RUSTFLAGS via env var, config, etc. is mutually
        # exclusive and often a source of bugs.
        # Empty string here means no override.
        rustflags: ""
