name: Setup Rust
description: Sets up Rust
inputs:
  toolchain:
    description: The Rust toolchain to use
    required: false
  components:
    description: Comma-separated list of components to install
    required: false
  cache:
    description: Automatically configure Rust cache
    default: true

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c #v1.15.2
      with:
        # Empty string means rust-toolchain if it exists, otherwise stable
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        cache: ${{ inputs.cache }}
        # Do not override the RUSTFLAGS by default and instead do that per job,
        # if needed. Setting RUSTFLAGS via env var, config, etc. is mutually
        # exclusive and often a source of bugs.
        # Empty string here means no override.
        rustflags: ""
        # By default, we do not override the toolchain from rust-toolchain.
        # The user needs to explicitly use `<cmd> +<toolchain>` for clarity.
        override: false
