name: Setup node
description: Sets up node and pnpm

inputs:
  node-version:
    description: Version of node to install
    required: false
    default: "22"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      id: setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
