name: Setup node
description: Sets up node and pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        cache: pnpm
