name: Setup node
description: Sets up node and pnpm

inputs:
  node-version:
    description: Version of node to install
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      id: setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
