use std::sync::OnceLock;

use alloy_rlp::RlpEncodable;
use k256::SecretKey;
use revm_primitives::keccak256;

use crate::{
    signature::{self, public_key_to_address, Fakeable, SignatureError},
    transaction::{self, TxKind},
    Address, Bytes, B256, U256,
};

#[derive(Clone, Debug, PartialEq, Eq, RlpEncodable)]
pub struct Legacy {
    // The order of these fields determines encoding order.
    pub nonce: u64,
    pub gas_price: U256,
    pub gas_limit: u64,
    pub kind: TxKind,
    pub value: U256,
    pub input: Bytes,
}

impl Legacy {
    /// The type identifier for a pre-EIP-155 legacy transaction.
    pub const TYPE: u8 = 0;

    /// Computes the hash of the transaction.
    pub fn hash(&self) -> B256 {
        keccak256(alloy_rlp::encode(self))
    }

    /// Signs the transaction with the provided secret key.
    pub fn sign(
        self,
        secret_key: &SecretKey,
    ) -> Result<transaction::signed::Legacy, SignatureError> {
        let caller = public_key_to_address(secret_key.public_key());

        // SAFETY: The caller is derived from the secret key.
        unsafe { self.sign_for_sender_unchecked(secret_key, caller) }
    }

    /// Signs the transaction with the provided secret key, belonging to the
    /// provided caller's address.
    ///
    /// # Safety
    ///
    /// The `caller` and `secret_key` must correspond to the same account.
    pub unsafe fn sign_for_sender_unchecked(
        self,
        secret_key: &SecretKey,
        caller: Address,
    ) -> Result<transaction::signed::Legacy, SignatureError> {
        let hash = self.hash();
        let signature = signature::SignatureWithRecoveryId::new(hash, secret_key)?;

        Ok(transaction::signed::Legacy {
            nonce: self.nonce,
            gas_price: self.gas_price,
            gas_limit: self.gas_limit,
            kind: self.kind,
            value: self.value,
            input: self.input,
            signature: Fakeable::with_address_unchecked(signature, caller),
            hash: OnceLock::new(),
        })
    }

    /// Creates a fake signature for an impersonated account.
    pub fn fake_sign(self, sender: Address) -> transaction::signed::Legacy {
        transaction::signed::Legacy {
            nonce: self.nonce,
            gas_price: self.gas_price,
            gas_limit: self.gas_limit,
            kind: self.kind,
            value: self.value,
            input: self.input,
            signature: signature::Fakeable::fake(sender, Some(0)),
            hash: OnceLock::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use super::*;
    use crate::transaction::fake_signature::tests::test_fake_sign_properties;

    fn dummy_request() -> Legacy {
        let to = Address::from_str("0xc014ba5ec014ba5ec014ba5ec014ba5ec014ba5e").unwrap();
        let input = hex::decode("1234").unwrap();
        Legacy {
            nonce: 1,
            gas_price: U256::from(2),
            gas_limit: 3,
            kind: TxKind::Call(to),
            value: U256::from(4),
            input: Bytes::from(input),
        }
    }

    #[test]
    fn test_legacy_transaction_request_encoding() {
        // Generated by Hardhat
        let expected =
            hex::decode("dc01020394c014ba5ec014ba5ec014ba5ec014ba5ec014ba5e04821234").unwrap();

        let request = dummy_request();

        let encoded = alloy_rlp::encode(&request);
        assert_eq!(expected, encoded);
    }

    #[test]
    fn test_legacy_transaction_request_hash() {
        // Generated by hardhat
        let expected = B256::from_slice(
            &hex::decode("41a46eddeeb251dc89bfe9d59ad27413909630a4c973dbdbbf23ab4aeed02818")
                .unwrap(),
        );

        let request = dummy_request();
        assert_eq!(expected, request.hash());
    }

    test_fake_sign_properties!();

    #[test]
    fn test_fake_sign_test_vector() -> anyhow::Result<()> {
        let transaction = Legacy {
            nonce: 0,
            gas_price: U256::from(678_912),
            gas_limit: 30_000,
            kind: TxKind::Call("0xb5bc06d4548a3ac17d72b372ae1e416bf65b8ead".parse()?),
            value: U256::from(1),
            input: Bytes::default(),
        };

        let fake_sender: Address = "0xa5bc06d4548a3ac17d72b372ae1e416bf65b8ead".parse()?;

        let signed = transaction.fake_sign(fake_sender);

        // Generated by Hardhat
        let expected_hash: B256 =
            "e2fea338f86a021a90028336d380e030030ff98466f13a0367061729232df0ca".parse()?;
        assert_eq!(signed.transaction_hash(), &expected_hash);

        Ok(())
    }
}
