packages:
  - "crates/edr_napi"
  - "hardhat-tests"
  - "hardhat-tests/integration/*"
  - "js/benchmark"
  - "js/helpers"
  - "js/integration-tests/*"

# Delay installs until a version is at least 1 week old
minimumReleaseAge: 10080

# Allow immediate installs for the following packages
minimumReleaseAgeExclude:
  - '@nomicfoundation/*'

onlyBuiltDependencies:
  - esbuild
  - keccak
  - secp256k1
