packages:
  - "crates/edr_napi"
  - "crates/tools/js/benchmark"
  - "hardhat-tests"
  - "hardhat-tests/integration/*"
  - "hardhat-solidity-tests"
  - "hardhat-solidity-tests/example"
  - "js/helpers"
  - "js/integration-tests/*"
