[package]
name = "edr_rpc_spec"
version.workspace = true
edition.workspace = true

[dependencies]
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
edr_utils.workspace = true
serde.workspace = true

[features]
test-utils = []

[lints]
workspace = true
