[package]
name = "edr_rpc_spec"
version.workspace = true
edition.workspace = true

[dependencies]
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
serde.workspace = true

[lints]
workspace = true
