[package]
name = "edr_chain_l1"
version.workspace = true
edition.workspace = true

[dependencies]
ambassador.workspace = true
anyhow = { workspace = true, optional = true }
alloy-rlp.workspace = true
alloy-serde.workspace = true
c-kzg.workspace = true
edr_eth.workspace = true
edr_evm.workspace = true
edr_provider.workspace = true
edr_rpc_eth.workspace = true
k256.workspace = true
log.workspace = true
paste.workspace = true
revm-context-interface.workspace = true
revm-handler.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
assert-json-diff = "2.0.2"
edr_defaults.workspace = true
edr_provider = { workspace = true, features = ["test-utils"] }
edr_rpc_eth = { workspace = true, features = ["test-utils"] }
edr_test_utils.workspace = true
serde_json.workspace = true

[features]
test-utils = ["dep:anyhow", "edr_provider/test-utils"]

[lints]
workspace = true
