//! slang-compiler build model, read from the per-source `debugSymbols`
//! output instead of the solc AST.

use std::{collections::HashMap, str::FromStr as _, sync::Arc};

use anyhow::{bail, Context as _};
use edr_primitives::hex;
use indexmap::IndexMap;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};

use super::{
    solc::CompiledContractsAndFiles,
    solx::{identify_contracts, SolxBuildModel},
    BuildInfo, BuildInfoOutput, BuildInfoWithOutput, CompilerInput, CompilerMetadataParseError,
    CompilerOutput, ContractAbiEntry, ContractMetadataExtractionError, JsonSource, SolxBytecode,
    SplitCompilerMetadataParseError,
};
use crate::{
    build_model::{
        Contract, ContractFunction, ContractFunctionType, ContractFunctionVisibility, ContractKind,
        SourceFile, SourceLocation,
    },
    contracts_identifier::IdentifiedContract,
};

/// Per-source symbol table emitted by the slang compiler under the
/// `debugSymbols` output selection.
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DebugSymbols {
    #[serde(default)]
    pub contracts: Vec<ContractSymbol>,
    #[serde(default)]
    pub free_functions: Vec<FunctionSymbol>,
    /// Range of every syntax node in the source.
    #[serde(default)]
    pub spans: Vec<SourceRange>,
}

/// A `[byteOffset, byteLength]` range into the source content.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(from = "[u32; 2]", into = "[u32; 2]")]
pub struct SourceRange {
    pub offset: u32,
    pub length: u32,
}

impl From<[u32; 2]> for SourceRange {
    fn from([offset, length]: [u32; 2]) -> Self {
        Self { offset, length }
    }
}

impl From<SourceRange> for [u32; 2] {
    fn from(range: SourceRange) -> Self {
        [range.offset, range.length]
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ContractSymbol {
    pub name: String,
    pub kind: ContractSymbolKind,
    #[serde(rename = "abstract", default)]
    pub is_abstract: bool,
    pub range: SourceRange,
    /// C3 linearization, the contract itself first.
    #[serde(default)]
    pub bases: Vec<ContractRef>,
    /// The contract's own members; inherited ones are resolved through
    /// `bases`.
    #[serde(default)]
    pub functions: Vec<FunctionSymbol>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ContractSymbolKind {
    Contract,
    Interface,
    Library,
    #[serde(other)]
    Unknown,
}

/// A contract identified by its source path and name.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ContractRef {
    pub path: String,
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionSymbol {
    pub name: String,
    pub kind: FunctionSymbolKind,
    pub visibility: Option<String>,
    pub mutability: Option<String>,
    /// Hex-encoded 4-byte selector of externally visible functions and
    /// getters.
    pub selector: Option<String>,
    pub range: SourceRange,
    #[serde(default = "default_implemented")]
    pub implemented: bool,
}

fn default_implemented() -> bool {
    true
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum FunctionSymbolKind {
    Function,
    Constructor,
    Fallback,
    Receive,
    Modifier,
    Getter,
    Free,
    #[serde(other)]
    Unknown,
}

/// Parses the compiler metadata generated by the slang compiler as a single
/// JSON file, extracts the contained compiler metadata, and returns a vector
/// of identified contracts.
pub fn parse_slang_compiler_metadata(
    metadata: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, CompilerMetadataParseError> {
    let BuildInfoWithOutput {
        _format,
        id: _,
        solc_version,
        solc_long_version: _,
        input,
        output,
    } = metadata.parse_json::<BuildInfoWithOutput<SolxBytecode>>()?;

    extract_slang_contract_metadata(solc_version, input, output)
        .map_err(CompilerMetadataParseError::from)
}

/// Parses the compiler metadata generated by the slang compiler as two
/// separate JSON files (one for the input and one for the output), extracts
/// the contained compiler metadata, and returns a vector of identified
/// contracts.
pub fn parse_split_slang_compiler_metadata(
    input: impl JsonSource,
    output: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, SplitCompilerMetadataParseError> {
    let BuildInfo {
        _format,
        id: input_id,
        solc_version,
        solc_long_version: _,
        input,
    } = input.parse_json::<BuildInfo>()?;

    let BuildInfoOutput {
        _format,
        id: output_id,
        output,
    } = output.parse_json::<BuildInfoOutput<SolxBytecode>>()?;

    if input_id != output_id {
        return Err(SplitCompilerMetadataParseError::IdMismatch {
            input_id,
            output_id: output_id.clone(),
        });
    }

    extract_slang_contract_metadata(solc_version, input, output)
        .map_err(SplitCompilerMetadataParseError::from)
}

/// Extracts [`IdentifiedContract`]s from the provided slang compiler input
/// and output.
///
/// `compiler_version` is not checked against the minimum supported solc
/// version: the slang compiler is versioned independently of solc.
pub fn extract_slang_contract_metadata(
    compiler_version: String,
    compiler_input: CompilerInput,
    compiler_output: CompilerOutput<SolxBytecode>,
) -> Result<Vec<IdentifiedContract>, ContractMetadataExtractionError> {
    let Some(build_model) = slang_build_model(compiler_input, &compiler_output)? else {
        return Ok(Vec::new());
    };

    identify_contracts(compiler_version, build_model, &compiler_output)
}

/// Builds the model from every source's `debugSymbols`, or returns `None`
/// when a source lacks them.
pub(crate) fn slang_build_model(
    compiler_input: CompilerInput,
    compiler_output: &CompilerOutput<SolxBytecode>,
) -> anyhow::Result<Option<SolxBuildModel>> {
    let mut sources = Vec::with_capacity(compiler_output.sources.len());
    for (source_name, source) in &compiler_output.sources {
        let Some(debug_symbols) = source.debug_symbols.as_ref() else {
            log::warn!(
                "The slang compiler output for {source_name} has no debugSymbols: it was \
                 produced without the \"debugSymbols\" output selection. Stack traces are \
                 unavailable for this compilation."
            );
            return Ok(None);
        };

        let content = match compiler_input.sources.get(source_name) {
            Some(input_source) => input_source.content.clone(),
            None => bail!("Compiler input missing source for {source_name}"),
        };
        let file = Arc::new(RwLock::new(SourceFile::new(source_name.clone(), content)));

        sources.push((source_name.as_str(), source.id, file, debug_symbols));
    }

    let mut contracts: IndexMap<(&str, &str), Arc<RwLock<Contract>>> = IndexMap::new();
    let mut ast_spans = HashMap::with_capacity(sources.len());

    for (source_name, file_id, file, debug_symbols) in &sources {
        let mut functions = Vec::new();

        for contract_symbol in &debug_symbols.contracts {
            let kind = match contract_symbol.kind {
                ContractSymbolKind::Contract => ContractKind::Contract,
                ContractSymbolKind::Library => ContractKind::Library,
                ContractSymbolKind::Interface | ContractSymbolKind::Unknown => continue,
            };

            let contract_abi = compiler_output
                .contracts
                .get(*source_name)
                .and_then(|contracts| contracts.get(&contract_symbol.name))
                .map(|contract| contract.abi.as_slice());

            let mut contract = Contract::new(
                contract_symbol.name.clone(),
                kind,
                SourceLocation::new(
                    file,
                    contract_symbol.range.offset,
                    contract_symbol.range.length,
                ),
            );

            for function_symbol in &contract_symbol.functions {
                let function =
                    contract_function(function_symbol, file, Some(&contract.name), contract_abi)
                        .with_context(|| {
                            format!(
                                "Invalid debugSymbols entry {}.{} in {source_name}",
                                contract_symbol.name, function_symbol.name
                            )
                        })?;

                if let Some(function) = function {
                    contract.add_local_function(function.clone())?;
                    functions.push(function);
                }
            }

            contracts.insert(
                (*source_name, contract_symbol.name.as_str()),
                Arc::new(RwLock::new(contract)),
            );
        }

        for function_symbol in &debug_symbols.free_functions {
            let function =
                contract_function(function_symbol, file, None, None).with_context(|| {
                    format!(
                        "Invalid debugSymbols entry {} in {source_name}",
                        function_symbol.name
                    )
                })?;
            functions.extend(function);
        }

        file.write().finalize(functions.into_boxed_slice());

        let mut spans: Vec<(u32, u32)> = debug_symbols
            .spans
            .iter()
            .map(|range| (range.offset, range.length))
            .collect();
        spans.sort_unstable();
        spans.dedup();
        ast_spans.insert(*file_id, spans);
    }

    for (source_name, _, _, debug_symbols) in &sources {
        for contract_symbol in &debug_symbols.contracts {
            let key = (*source_name, contract_symbol.name.as_str());
            let Some(contract) = contracts.get(&key) else {
                continue;
            };
            let mut contract = contract.write();

            for base in &contract_symbol.bases {
                let base_key = (base.path.as_str(), base.name.as_str());
                if base_key == key {
                    continue;
                }
                // Interfaces are not modelled.
                let Some(base_contract) = contracts.get(&base_key) else {
                    continue;
                };
                contract.add_next_linearized_base_contract(&base_contract.read())?;
            }
        }
    }

    // Contracts absent from the output's `contracts` only serve as bases.
    let contract_id_to_contract = (0u32..)
        .zip(
            contracts
                .into_iter()
                .filter_map(|((file, name), contract)| {
                    compiler_output
                        .contracts
                        .get(file)
                        .is_some_and(|contracts| contracts.contains_key(name))
                        .then_some(contract)
                }),
        )
        .collect();

    let file_id_to_source_file = sources
        .into_iter()
        .map(|(_, file_id, file, _)| (file_id, file))
        .collect();

    Ok(Some(SolxBuildModel::from_parts(
        CompiledContractsAndFiles {
            contract_id_to_contract,
            file_id_to_source_file,
        },
        ast_spans,
    )))
}

fn contract_function(
    symbol: &FunctionSymbol,
    file: &Arc<RwLock<SourceFile>>,
    contract_name: Option<&str>,
    contract_abi: Option<&[ContractAbiEntry]>,
) -> anyhow::Result<Option<Arc<ContractFunction>>> {
    let function_type = match symbol.kind {
        FunctionSymbolKind::Function => ContractFunctionType::Function,
        FunctionSymbolKind::Constructor => ContractFunctionType::Constructor,
        FunctionSymbolKind::Fallback => ContractFunctionType::Fallback,
        FunctionSymbolKind::Receive => ContractFunctionType::Receive,
        FunctionSymbolKind::Modifier => ContractFunctionType::Modifier,
        FunctionSymbolKind::Getter => ContractFunctionType::Getter,
        FunctionSymbolKind::Free => ContractFunctionType::FreeFunction,
        FunctionSymbolKind::Unknown => return Ok(None),
    };

    let location = SourceLocation::new(file, symbol.range.offset, symbol.range.length);
    let contract_name = contract_name.map(str::to_owned);

    if function_type == ContractFunctionType::Modifier {
        return Ok(Some(Arc::new(ContractFunction {
            name: symbol.name.clone(),
            r#type: function_type,
            location,
            contract_name,
            visibility: None,
            is_payable: None,
            selector: RwLock::new(None),
            param_types: None,
        })));
    }

    if !symbol.implemented {
        return Ok(None);
    }

    let visibility = symbol
        .visibility
        .as_deref()
        .and_then(|visibility| ContractFunctionVisibility::from_str(visibility).ok())
        .unwrap_or_default();

    let has_selector = match function_type {
        ContractFunctionType::Function => matches!(
            visibility,
            ContractFunctionVisibility::Public | ContractFunctionVisibility::External
        ),
        ContractFunctionType::Getter => true,
        _ => false,
    };

    let selector = if has_selector {
        let selector = symbol
            .selector
            .as_deref()
            .context("Externally visible function has no selector")?;
        Some(hex::decode(selector).with_context(|| format!("Failed to decode hex: {selector:?}"))?)
    } else {
        None
    };

    let abi_entry = contract_abi.and_then(|abi| {
        let mut functions_named = abi.iter().filter(|entry| {
            entry.r#type.as_deref() == Some("function")
                && entry.name.as_deref() == Some(&symbol.name)
        });
        if function_type == ContractFunctionType::Getter {
            functions_named.next()
        } else {
            let selector = selector.as_deref()?;
            functions_named.find(|entry| {
                abi_entry_selector(entry).is_some_and(|abi_selector| abi_selector == selector)
            })
        }
    });

    Ok(Some(Arc::new(ContractFunction {
        name: symbol.name.clone(),
        r#type: function_type,
        location,
        contract_name,
        visibility: Some(visibility),
        is_payable: Some(symbol.mutability.as_deref() == Some("payable")),
        selector: RwLock::new(selector),
        param_types: abi_entry.and_then(|entry| entry.inputs.clone()),
    })))
}

fn abi_entry_selector(entry: &ContractAbiEntry) -> Option<[u8; 4]> {
    let inputs = entry
        .inputs
        .iter()
        .flatten()
        .map(|input| serde_json::from_value(input.clone()))
        .collect::<Result<Vec<alloy_json_abi::Param>, _>>()
        .ok()?;

    let function = alloy_json_abi::Function {
        name: entry.name.clone()?,
        inputs,
        outputs: Vec::new(),
        state_mutability: alloy_json_abi::StateMutability::NonPayable,
    };

    Some(function.selector().0)
}

#[cfg(test)]
mod tests {
    use edr_primitives::keccak256;
    use serde_json::json;

    use super::*;
    use crate::{
        artifacts::{
            BuildInfoBufferSeparateOutput, BuildInfoBuffers, BuildInfoConfig,
            BuildInfoConfigWithBuffers,
        },
        build_model::BuildModel as _,
        debug_info::dwarf::SourceLookup as _,
    };

    const A_SOL: &str = r#"// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

function helper(uint256 x) pure returns (uint256) {
    return x + 1;
}

interface IThing {
    function thing() external view returns (uint256);
}

library Lib {
    function twice(uint256 x) internal pure returns (uint256) {
        return x * 2;
    }
}

abstract contract Root is IThing {
    uint256 public count;

    modifier onlyPositive(uint256 x) {
        require(x > 0);
        _;
    }

    function thing() external view virtual returns (uint256) {
        return count;
    }

    function todo() public virtual;

    function set(uint256 x) public virtual onlyPositive(x) {
        count = x;
    }

    function set(uint256 x, uint256 y) public {
        count = x + y;
    }
}
"#;

    const B_SOL: &str = r#"import "A.sol";

contract Left is Root {
    function set(uint256 x) public virtual override {
        count = x * 2;
    }

    function todo() public virtual override {}
}

contract Right is Root {
    function todo() public virtual override {}
}

contract Diamond is Left, Right {
    constructor() payable {}

    fallback() external {}

    receive() external payable {}

    function todo() public override(Left, Right) {}
}
"#;

    /// `[offset, length]` from the start of `start` up to and including the
    /// first `end` after it.
    fn range(source: &str, start: &str, end: &str) -> SourceRange {
        let offset = source.find(start).expect("start marker in source");
        let end_offset =
            offset + source[offset..].find(end).expect("end marker after start") + end.len();
        SourceRange {
            offset: offset as u32,
            length: (end_offset - offset) as u32,
        }
    }

    fn selector(signature: &str) -> String {
        hex::encode(&keccak256(signature.as_bytes())[..4])
    }

    fn function(
        name: &str,
        kind: &str,
        visibility: &str,
        mutability: &str,
        signature: Option<&str>,
        range: SourceRange,
    ) -> serde_json::Value {
        let mut function = json!({
            "name": name,
            "kind": kind,
            "visibility": visibility,
            "mutability": mutability,
            "range": range,
            "implemented": true,
        });
        if let Some(signature) = signature {
            function["selector"] = json!(selector(signature));
        }
        function
    }

    fn base(path: &str, name: &str) -> serde_json::Value {
        json!({ "path": path, "name": name })
    }

    fn a_sol_debug_symbols() -> serde_json::Value {
        let s = A_SOL;
        let root_body = "\n}\n";
        let mut todo = function(
            "todo",
            "function",
            "public",
            "nonpayable",
            Some("todo()"),
            range(s, "function todo() public virtual;", ";"),
        );
        todo["implemented"] = json!(false);

        json!({
            "contracts": [
                {
                    "name": "IThing", "kind": "interface", "abstract": false,
                    "range": range(s, "interface IThing", root_body),
                    "bases": [base("A.sol", "IThing")],
                    "functions": [function(
                        "thing", "function", "external", "view", Some("thing()"),
                        range(s, "function thing() external view returns", ";"),
                    )],
                },
                {
                    "name": "Lib", "kind": "library", "abstract": false,
                    "range": range(s, "library Lib", root_body),
                    "functions": [function(
                        "twice", "function", "internal", "pure", None,
                        range(s, "function twice", "\n    }"),
                    )],
                },
                {
                    "name": "Root", "kind": "contract", "abstract": true,
                    "range": range(s, "abstract contract Root", root_body),
                    "bases": [base("A.sol", "Root"), base("A.sol", "IThing")],
                    "functions": [
                        function(
                            "count", "getter", "external", "view", Some("count()"),
                            range(s, "uint256 public count", ";"),
                        ),
                        function(
                            "onlyPositive", "modifier", "internal", "nonpayable", None,
                            range(s, "modifier onlyPositive", "\n    }"),
                        ),
                        function(
                            "thing", "function", "external", "view", Some("thing()"),
                            range(s, "function thing() external view virtual", "\n    }"),
                        ),
                        todo,
                        function(
                            "set", "function", "public", "nonpayable", Some("set(uint256)"),
                            range(s, "function set(uint256 x) public", "\n    }"),
                        ),
                        function(
                            "set", "function", "public", "nonpayable",
                            Some("set(uint256,uint256)"),
                            range(s, "function set(uint256 x, uint256 y)", "\n    }"),
                        ),
                    ],
                },
            ],
            "freeFunctions": [function(
                "helper", "free", "internal", "pure", None,
                range(s, "function helper", "\n}"),
            )],
            // Unsorted, with a duplicate.
            "spans": [
                range(s, "count = x;", ";"),
                [0, s.len()],
                range(s, "abstract contract Root", root_body),
                range(s, "function set(uint256 x) public", "\n    }"),
                range(s, "count = x;", ";"),
            ],
        })
    }

    fn b_sol_debug_symbols() -> serde_json::Value {
        let s = B_SOL;
        let contract_end = "\n}\n";
        json!({
            "contracts": [
                {
                    "name": "Left", "kind": "contract", "abstract": false,
                    "range": range(s, "contract Left", contract_end),
                    "bases": [base("B.sol", "Left"), base("A.sol", "Root"), base("A.sol", "IThing")],
                    "functions": [
                        function(
                            "set", "function", "public", "nonpayable", Some("set(uint256)"),
                            range(s, "function set(uint256 x) public virtual override", "\n    }"),
                        ),
                        function(
                            "todo", "function", "public", "nonpayable", Some("todo()"),
                            range(s, "function todo() public virtual override {}", "}"),
                        ),
                    ],
                },
                {
                    "name": "Right", "kind": "contract", "abstract": false,
                    "range": range(s, "contract Right", contract_end),
                    "bases": [base("B.sol", "Right"), base("A.sol", "Root"), base("A.sol", "IThing")],
                    "functions": [function(
                        "todo", "function", "public", "nonpayable", Some("todo()"),
                        range(s, "contract Right is Root {\n    function todo()", "}"),
                    )],
                },
                {
                    "name": "Diamond", "kind": "contract", "abstract": false,
                    "range": range(s, "contract Diamond", contract_end),
                    "bases": [
                        base("B.sol", "Diamond"),
                        base("B.sol", "Right"),
                        base("B.sol", "Left"),
                        base("A.sol", "Root"),
                        base("A.sol", "IThing"),
                    ],
                    "functions": [
                        function(
                            "constructor", "constructor", "public", "payable", None,
                            range(s, "constructor()", "}"),
                        ),
                        function(
                            "fallback", "fallback", "external", "nonpayable", None,
                            range(s, "fallback()", "}"),
                        ),
                        function(
                            "receive", "receive", "external", "payable", None,
                            range(s, "receive()", "}"),
                        ),
                        function(
                            "todo", "function", "public", "nonpayable", Some("todo()"),
                            range(s, "function todo() public override(Left, Right)", "}"),
                        ),
                    ],
                },
            ],
            "spans": [[0, s.len()]],
        })
    }

    fn abi_function(name: &str, inputs: &[&str]) -> serde_json::Value {
        let inputs: Vec<_> = inputs
            .iter()
            .enumerate()
            .map(|(index, ty)| json!({ "name": format!("arg{index}"), "type": ty, "internalType": ty }))
            .collect();
        json!({ "type": "function", "name": name, "inputs": inputs })
    }

    fn output_contract(abi: Vec<serde_json::Value>) -> serde_json::Value {
        let bytecode = json!({
            "object": "",
            "opcodes": "",
            "debugInfo": "",
            "linkReferences": {},
        });
        json!({
            "abi": abi,
            "evm": {
                "bytecode": bytecode,
                "deployedBytecode": bytecode,
                "methodIdentifiers": {},
            },
        })
    }

    fn diamond_input_output() -> (serde_json::Value, serde_json::Value) {
        let input = json!({
            "language": "Solidity",
            "sources": {
                "A.sol": { "content": A_SOL },
                "B.sol": { "content": B_SOL },
            },
        });

        let root_abi = vec![
            abi_function("count", &[]),
            abi_function("set", &["uint256", "uint256"]),
            abi_function("set", &["uint256"]),
            abi_function("thing", &[]),
            abi_function("todo", &[]),
        ];
        let output = json!({
            "sources": {
                "A.sol": { "id": 0, "debugSymbols": a_sol_debug_symbols() },
                "B.sol": { "id": 1, "debugSymbols": b_sol_debug_symbols() },
            },
            "contracts": {
                "A.sol": {
                    "Lib": output_contract(Vec::new()),
                    "Root": output_contract(root_abi.clone()),
                },
                "B.sol": {
                    "Left": output_contract(root_abi.clone()),
                    "Right": output_contract(root_abi.clone()),
                    "Diamond": output_contract(root_abi),
                },
            },
        });

        (input, output)
    }

    fn diamond_build_model() -> SolxBuildModel {
        let (input, output) = diamond_input_output();
        let input: CompilerInput = serde_json::from_value(input).unwrap();
        let output: CompilerOutput<SolxBytecode> = serde_json::from_value(output).unwrap();
        slang_build_model(input, &output)
            .expect("debugSymbols are valid")
            .expect("every source has debugSymbols")
    }

    fn contract_named(model: &SolxBuildModel, name: &str) -> Arc<RwLock<Contract>> {
        model
            .contracts()
            .find(|contract| contract.read().name == name)
            .unwrap_or_else(|| panic!("{name} is in the model"))
            .clone()
    }

    /// Name of the contract declaring the function `contract` dispatches
    /// `signature` to.
    fn dispatched_to(contract: &Contract, signature: &str) -> Option<String> {
        let selector = hex::decode(selector(signature)).unwrap();
        contract
            .get_function_from_selector(&selector)
            .map(|function| function.contract_name.clone().expect("contract function"))
    }

    fn function_containing(
        model: &SolxBuildModel,
        file_id: u32,
        marker: &str,
    ) -> Option<Arc<ContractFunction>> {
        let file = model.source_model_by_file_id(file_id).unwrap();
        let offset = file.read().content.find(marker).expect("marker in source") as u32;
        SourceLocation::new(file, offset, 1)
            .get_containing_function()
            .unwrap()
    }

    #[test]
    fn deserializes_the_debug_symbols_table() {
        let table: DebugSymbols = serde_json::from_value(json!({
            "contracts": [{
                "name": "Counter", "kind": "contract", "abstract": false,
                "range": [120, 860],
                "bases": [{"path": "Counter.sol", "name": "Counter"}, {"path": "Base.sol", "name": "Base"}],
                "functions": [
                    {"name": "inc", "kind": "function", "visibility": "public", "mutability": "nonpayable", "selector": "371303c0", "range": [300, 120], "implemented": true},
                    {"name": "onlyOwner", "kind": "modifier", "visibility": "internal", "mutability": "nonpayable", "range": [200, 90], "implemented": true},
                    {"name": "count", "kind": "getter", "visibility": "external", "mutability": "view", "selector": "06661abd", "range": [140, 30], "implemented": true},
                    {"name": "constructor", "kind": "constructor", "visibility": "public", "mutability": "nonpayable", "range": [230, 60], "implemented": true}
                ]
            }],
            "freeFunctions": [{"name": "helper", "kind": "free", "visibility": "internal", "mutability": "pure", "range": [20, 90], "implemented": true}],
            "spans": [[0, 1200], [20, 90], [120, 860]],
            "unknownField": {"ignored": true}
        }))
        .unwrap();

        let contract = table.contracts.first().unwrap();
        assert_eq!(contract.name, "Counter");
        assert_eq!(contract.kind, ContractSymbolKind::Contract);
        assert!(!contract.is_abstract);
        assert_eq!(
            contract.range,
            SourceRange {
                offset: 120,
                length: 860
            }
        );
        assert_eq!(
            contract.bases,
            vec![
                ContractRef {
                    path: "Counter.sol".into(),
                    name: "Counter".into()
                },
                ContractRef {
                    path: "Base.sol".into(),
                    name: "Base".into()
                },
            ]
        );
        let kinds: Vec<_> = contract.functions.iter().map(|f| f.kind).collect();
        assert_eq!(
            kinds,
            [
                FunctionSymbolKind::Function,
                FunctionSymbolKind::Modifier,
                FunctionSymbolKind::Getter,
                FunctionSymbolKind::Constructor,
            ]
        );
        let inc = contract.functions.first().unwrap();
        assert_eq!(inc.selector.as_deref(), Some("371303c0"));
        assert_eq!(inc.visibility.as_deref(), Some("public"));
        assert_eq!(inc.mutability.as_deref(), Some("nonpayable"));
        assert_eq!(
            inc.range,
            SourceRange {
                offset: 300,
                length: 120
            }
        );
        assert!(contract
            .functions
            .iter()
            .filter(|f| f.kind == FunctionSymbolKind::Modifier)
            .all(|f| f.selector.is_none()));

        let helper = table.free_functions.first().unwrap();
        assert_eq!(helper.kind, FunctionSymbolKind::Free);
        assert_eq!(table.spans.len(), 3);
    }

    #[test]
    fn deserialization_tolerates_missing_optional_fields_and_new_kinds() {
        let table: DebugSymbols = serde_json::from_value(json!({
            "contracts": [{
                "name": "C", "kind": "somethingNew", "range": [0, 1],
                "functions": [{"name": "f", "kind": "somethingNew", "range": [0, 1]}]
            }]
        }))
        .unwrap();

        let contract = table.contracts.first().unwrap();
        assert_eq!(contract.kind, ContractSymbolKind::Unknown);
        assert!(contract.bases.is_empty());
        let function = contract.functions.first().unwrap();
        assert_eq!(function.kind, FunctionSymbolKind::Unknown);
        assert!(function.implemented);
        assert!(table.free_functions.is_empty());
        assert!(table.spans.is_empty());
    }

    #[test]
    fn models_contracts_without_interfaces_in_source_order() {
        let model = diamond_build_model();

        let contracts: Vec<_> = model
            .contracts()
            .map(|contract| {
                let contract = contract.read();
                (
                    contract.name.clone(),
                    contract.location.file().unwrap().read().source_name.clone(),
                )
            })
            .collect();
        assert_eq!(
            contracts,
            [
                ("Lib".to_string(), "A.sol".to_string()),
                ("Root".to_string(), "A.sol".to_string()),
                ("Left".to_string(), "B.sol".to_string()),
                ("Right".to_string(), "B.sol".to_string()),
                ("Diamond".to_string(), "B.sol".to_string()),
            ]
        );

        assert_eq!(
            contract_named(&model, "Lib").read().r#type,
            ContractKind::Library
        );
        assert_eq!(
            contract_named(&model, "Root").read().r#type,
            ContractKind::Contract
        );

        let root = contract_named(&model, "Root");
        let root = root.read();
        let expected = range(A_SOL, "abstract contract Root", "\n}\n");
        assert_eq!(
            (root.location.offset, root.location.length),
            (expected.offset, expected.length)
        );
        assert_eq!(root.location.get_starting_line_number().unwrap(), 18);

        assert!(
            function_containing(&model, 0, "function thing() external view returns").is_none(),
            "interface members are not modelled"
        );
    }

    #[test]
    fn models_local_functions() {
        let model = diamond_build_model();

        let root = contract_named(&model, "Root");
        let root = root.read();

        let set_one = root
            .get_function_from_selector(&hex::decode(selector("set(uint256)")).unwrap())
            .unwrap();
        assert_eq!(set_one.r#type, ContractFunctionType::Function);
        assert_eq!(set_one.visibility, Some(ContractFunctionVisibility::Public));
        assert_eq!(set_one.is_payable, Some(false));
        assert_eq!(set_one.param_types.as_ref().map(Vec::len), Some(1));

        let set_two = root
            .get_function_from_selector(&hex::decode(selector("set(uint256,uint256)")).unwrap())
            .unwrap();
        assert_eq!(set_two.param_types.as_ref().map(Vec::len), Some(2));
        assert_eq!(
            set_two.location.offset,
            range(A_SOL, "function set(uint256 x, uint256 y)", "\n    }").offset,
            "overloads keep their own locations"
        );

        let thing = root
            .get_function_from_selector(&hex::decode(selector("thing()")).unwrap())
            .unwrap();
        assert_eq!(thing.visibility, Some(ContractFunctionVisibility::External));

        let count = root
            .get_function_from_selector(&hex::decode(selector("count()")).unwrap())
            .unwrap();
        assert_eq!(count.r#type, ContractFunctionType::Getter);
        assert_eq!(count.is_payable, Some(false));
        assert_eq!(count.param_types.as_ref().map(Vec::len), Some(0));

        assert!(
            root.get_function_from_selector(&hex::decode(selector("todo()")).unwrap())
                .is_none(),
            "unimplemented functions are skipped"
        );
        assert!(function_containing(&model, 0, "function todo() public virtual;").is_none());

        let modifier = function_containing(&model, 0, "require(x > 0)").unwrap();
        assert_eq!(modifier.name, "onlyPositive");
        assert_eq!(modifier.r#type, ContractFunctionType::Modifier);
        assert_eq!(modifier.contract_name.as_deref(), Some("Root"));
        assert_eq!(modifier.visibility, None);
        assert_eq!(*modifier.selector.read(), None);

        let twice = function_containing(&model, 0, "return x * 2").unwrap();
        assert_eq!(twice.contract_name.as_deref(), Some("Lib"));
        assert_eq!(twice.visibility, Some(ContractFunctionVisibility::Internal));
        assert_eq!(*twice.selector.read(), None);

        let helper = function_containing(&model, 0, "return x + 1").unwrap();
        assert_eq!(helper.name, "helper");
        assert_eq!(helper.r#type, ContractFunctionType::FreeFunction);
        assert_eq!(helper.contract_name, None);

        let diamond = contract_named(&model, "Diamond");
        let diamond = diamond.read();
        let constructor = diamond.constructor.as_ref().unwrap();
        assert_eq!(constructor.r#type, ContractFunctionType::Constructor);
        assert_eq!(constructor.is_payable, Some(true));
        assert_eq!(
            diamond.fallback.as_ref().unwrap().r#type,
            ContractFunctionType::Fallback
        );
        assert_eq!(diamond.receive.as_ref().unwrap().is_payable, Some(true));
    }

    #[test]
    fn resolves_inherited_functions_in_linearization_order() {
        let model = diamond_build_model();

        let diamond = contract_named(&model, "Diamond");
        let diamond = diamond.read();
        assert_eq!(
            dispatched_to(&diamond, "todo()").as_deref(),
            Some("Diamond")
        );
        assert_eq!(
            dispatched_to(&diamond, "set(uint256)").as_deref(),
            Some("Left")
        );
        assert_eq!(
            dispatched_to(&diamond, "set(uint256,uint256)").as_deref(),
            Some("Root")
        );
        assert_eq!(dispatched_to(&diamond, "thing()").as_deref(), Some("Root"));
        assert_eq!(dispatched_to(&diamond, "count()").as_deref(), Some("Root"));

        let right = contract_named(&model, "Right");
        let right = right.read();
        assert_eq!(dispatched_to(&right, "todo()").as_deref(), Some("Right"));
        assert_eq!(
            dispatched_to(&right, "set(uint256)").as_deref(),
            Some("Root")
        );
        assert!(right.constructor.is_none());
        assert!(right.fallback.is_none());

        let left = contract_named(&model, "Left");
        assert_eq!(
            dispatched_to(&left.read(), "todo()").as_deref(),
            Some("Left")
        );
    }

    #[test]
    fn looks_up_spans_and_sources() {
        let model = diamond_build_model();

        let statement = range(A_SOL, "count = x;", ";");
        let inside_statement = statement.offset + 3;
        assert_eq!(
            model.smallest_enclosing_span(0, inside_statement),
            Some((statement.offset, statement.length))
        );

        let set_one = range(A_SOL, "function set(uint256 x) public", "\n    }");
        assert_eq!(
            model.smallest_enclosing_span(0, set_one.offset),
            Some((set_one.offset, set_one.length))
        );

        assert_eq!(
            model.smallest_enclosing_span(0, 0),
            Some((0, A_SOL.len() as u32))
        );
        assert_eq!(model.smallest_enclosing_span(0, A_SOL.len() as u32), None);
        assert_eq!(model.smallest_enclosing_span(7, 0), None);

        for (file_id, source_name) in [(0, "A.sol"), (1, "B.sol")] {
            let file = model.source_model_by_file_id(file_id).unwrap();
            assert_eq!(file.read().source_name, source_name);
            assert_eq!(model.file_id_by_name(source_name), Some(file_id));
        }
        assert!(model.source_model_by_file_id(2).is_none());
    }

    #[test]
    fn missing_debug_symbols_contribute_no_contracts() {
        let (input, mut output) = diamond_input_output();
        output["sources"]["B.sol"]
            .as_object_mut()
            .unwrap()
            .remove("debugSymbols");

        let input: CompilerInput = serde_json::from_value(input).unwrap();
        let output: CompilerOutput<SolxBytecode> = serde_json::from_value(output).unwrap();

        let contracts = extract_slang_contract_metadata("0.1.0".to_string(), input, output)
            .expect("a missing table is not an error");
        assert!(contracts.is_empty());
    }

    /// Counter fixture with its solc AST replaced by a hand-written
    /// `debugSymbols` table.
    fn counter_build_info(compiler_version: &str) -> (serde_json::Value, serde_json::Value) {
        let content = include_str!("../../fixtures/sources/Counter.sol");
        let mut input: serde_json::Value =
            serde_json::from_str(include_str!("../../fixtures/solx_compiler_input.json")).unwrap();
        input["sources"]["Counter.sol"]["content"] = json!(content);

        let mut output: serde_json::Value =
            serde_json::from_str(include_str!("../../fixtures/solx_compiler_output.json")).unwrap();
        let source = output["sources"]["Counter.sol"].as_object_mut().unwrap();
        source.remove("ast");
        source.insert(
            "debugSymbols".to_string(),
            json!({
                "contracts": [{
                    "name": "Counter", "kind": "contract", "abstract": false,
                    "range": range(content, "contract Counter", "\n}"),
                    "bases": [base("Counter.sol", "Counter")],
                    "functions": [
                        function(
                            "count", "getter", "external", "view", Some("count()"),
                            range(content, "uint256 public count", ";"),
                        ),
                        function(
                            "set", "function", "public", "nonpayable", Some("set(uint256)"),
                            range(content, "function set", "\n  }"),
                        ),
                        function(
                            "_checkPositive", "function", "internal", "pure", None,
                            range(content, "function _checkPositive", "\n  }"),
                        ),
                    ],
                }],
                "spans": [
                    [0, content.len()],
                    range(content, "contract Counter", "\n}"),
                    range(content, "function _checkPositive", "\n  }"),
                    range(content, "require(", ";"),
                ],
            }),
        );

        let build_info = json!({
            "_format": "hh-sol-build-info-1",
            "id": "slang-counter",
            "solcVersion": compiler_version,
            "solcLongVersion": compiler_version,
            "compilerType": "slang",
            "input": input,
        });
        let build_info_output = json!({
            "_format": "hh-sol-build-info-output-1",
            "id": "slang-counter",
            "output": output,
        });
        (build_info, build_info_output)
    }

    fn assert_counter_decodes(contracts: &[IdentifiedContract]) {
        assert_eq!(contracts.len(), 2, "creation and runtime bytecode");

        let runtime = contracts
            .iter()
            .find(|contract| !contract.contract_metadata.is_deployment)
            .unwrap();
        assert_eq!(runtime.contract_metadata.contract.read().name, "Counter");

        let require_line = (0..runtime.contract_metadata.normalized_code.len() as u32)
            .filter_map(|pc| runtime.contract_metadata.get_instruction(pc).ok())
            .filter_map(|instruction| instruction.location.as_ref())
            .find(|location| location.get_starting_line_number().unwrap() == 13)
            .expect("an instruction maps to the require on line 13");
        let function = require_line.get_containing_function().unwrap().unwrap();
        assert_eq!(function.name, "_checkPositive");
        assert!(
            require_line.length > 0,
            "length comes from debugSymbols spans"
        );
    }

    #[test]
    fn slang_compiler_type_round_trips_through_build_info_parsing() {
        // A slang compiler version, below the minimum solc version.
        let (build_info, build_info_output) = counter_build_info("0.1.0");
        let mut with_output = build_info.clone();
        with_output["output"] = build_info_output["output"].clone();
        let with_output = with_output.to_string();
        let build_info = build_info.to_string();
        let build_info_output = build_info_output.to_string();

        let combined = BuildInfoConfig::parse_from_buffers(BuildInfoConfigWithBuffers {
            build_infos: Some(BuildInfoBuffers::WithOutput(vec![with_output.as_bytes()])),
            ignore_contracts: None,
        })
        .unwrap();
        assert_counter_decodes(&combined.identified_contracts);

        let separate = BuildInfoConfig::parse_from_buffers(BuildInfoConfigWithBuffers {
            build_infos: Some(BuildInfoBuffers::SeparateInputOutput(vec![
                BuildInfoBufferSeparateOutput {
                    build_info: build_info.as_bytes(),
                    output: build_info_output.as_bytes(),
                },
            ])),
            ignore_contracts: None,
        })
        .unwrap();
        assert_counter_decodes(&separate.identified_contracts);
    }
}
