//! solc-specific build model types.

mod ast;
mod source_map;

use std::{collections::HashMap, sync::Arc};

use anyhow::{bail, Context as _};
use indexmap::IndexMap;
use parking_lot::RwLock;
use revm_bytecode::OpCode;

use self::{
    ast::process_ast_nodes,
    source_map::{add_unmapped_instructions, uncompress_sourcemaps},
};
use super::{
    BuildInfoWithOutput, CompilerArtifact, CompilerInput, CompilerMetadataParseError,
    CompilerOutput, ContractMetadataExtractionError, InvalidSolcVersionError, JsonSource,
    SolcBytecode, UnsupportedSolcVersionError,
};
use crate::{
    artifacts::{BuildInfo, BuildInfoOutput, SplitCompilerMetadataParseError},
    build_model::{BuildModel, Contract, Instruction, JumpType, SourceFile, SourceLocation},
    compiler::{correct_selectors, decode_bytecodes, FIRST_SOLC_VERSION_SUPPORTED},
    contracts_identifier::IdentifiedContract,
    trace_strategy::SOLC_TRACE_STRATEGY,
};

pub(super) struct CompiledContractsAndFiles {
    // TODO https://github.com/NomicFoundation/edr/issues/759
    /// Maps the contract ID to the contract.
    pub contract_id_to_contract: IndexMap<u32, Arc<RwLock<Contract>>>,
    /// Maps the file ID to the source file.
    pub file_id_to_source_file: HashMap<u32, Arc<RwLock<SourceFile>>>,
}

pub(super) fn collect_compiled_contracts_and_files<ArtifactT: CompilerArtifact>(
    input: CompilerInput,
    output: &CompilerOutput<ArtifactT>,
) -> anyhow::Result<CompiledContractsAndFiles> {
    // First, collect and store all the files to be able to resolve the source
    // locations
    let file_id_to_source_file = output
        .sources
        .iter()
        .map(|(source_name, source)| {
            let file = SourceFile::new(
                source_name.clone(),
                input.sources.get(source_name).map_or_else(
                    || bail!("Compiler input missing source for {source_name}"),
                    |source| Ok(source.content.clone()),
                )?,
            );

            let file = Arc::new(RwLock::new(file));
            Ok((source.id, file))
        })
        .collect::<anyhow::Result<HashMap<_, _>>>()?;

    // Secondly, collect all the contracts and fill the source file/contracts with
    // processed functions
    let mut contract_id_to_linearized_base_contract_ids = HashMap::new();
    let mut contract_id_to_contract = IndexMap::new();

    for (source_name, source) in &output.sources {
        let mut file = file_id_to_source_file
            .get(&source.id)
            .expect("source.id should exist in sources")
            .write();

        process_ast_nodes(
            &mut file,
            source_name,
            &source.ast,
            &file_id_to_source_file,
            output,
            &mut contract_id_to_linearized_base_contract_ids,
            &mut contract_id_to_contract,
        )
        .with_context(|| format!("Failed to process AST for {source_name}"))?;
    }

    apply_contracts_inheritance(
        &contract_id_to_contract,
        &contract_id_to_linearized_base_contract_ids,
    )?;

    Ok(CompiledContractsAndFiles {
        contract_id_to_contract,
        file_id_to_source_file,
    })
}

fn apply_contracts_inheritance(
    contract_id_to_contract: &IndexMap<u32, Arc<RwLock<Contract>>>,
    contract_id_to_linearized_base_contract_ids: &HashMap<u32, Vec<u32>>,
) -> anyhow::Result<()> {
    for (cid, contract) in contract_id_to_contract {
        let mut contract = contract.write();

        let inheritance_ids = &contract_id_to_linearized_base_contract_ids[cid];

        for base_id in inheritance_ids {
            let base_contract = contract_id_to_contract.get(base_id);

            let base_contract = match base_contract {
                Some(base_contract) => base_contract,
                // This list includes interface, which we don't model
                None => continue,
            };

            if cid != base_id {
                let base_contract = &base_contract.read();
                contract.add_next_linearized_base_contract(base_contract)?;
            }
        }
    }
    Ok(())
}

/// Parses the compiler metadata generated by solc as a single JSON file,
/// extracts the contained compiler metadata, and returns a vector of identified
/// contracts.
pub fn parse_solc_compiler_metadata(
    metadata: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, CompilerMetadataParseError> {
    let BuildInfoWithOutput {
        _format,
        id: _,
        solc_version,
        solc_long_version: _,
        input,
        output,
    } = metadata.parse_json::<BuildInfoWithOutput<SolcBytecode>>()?;

    extract_solc_contract_metadata(solc_version, input, output)
        .map_err(CompilerMetadataParseError::from)
}

/// Parses the compiler metadata generated by solc as two separate JSON files
/// (one for the input and one for the output), extracts the contained compiler
/// metadata, and returns a vector of identified contracts.
pub fn parse_split_solc_compiler_metadata(
    input: impl JsonSource,
    output: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, SplitCompilerMetadataParseError> {
    let BuildInfo {
        _format,
        id: input_id,
        solc_version,
        solc_long_version: _,
        input,
    } = input.parse_json::<BuildInfo>()?;

    let BuildInfoOutput {
        _format,
        id: output_id,
        output,
    } = output.parse_json::<BuildInfoOutput<SolcBytecode>>()?;

    if input_id != output_id {
        return Err(SplitCompilerMetadataParseError::IdMismatch {
            input_id,
            output_id: output_id.clone(),
        });
    }

    extract_solc_contract_metadata(solc_version, input, output)
        .map_err(SplitCompilerMetadataParseError::from)
}

/// Extracts [`IdentifiedContract`]s from the provided solc compiler input and
/// output.
pub fn extract_solc_contract_metadata(
    solc_version: String,
    compiler_input: CompilerInput,
    compiler_output: CompilerOutput<SolcBytecode>,
) -> Result<Vec<IdentifiedContract>, ContractMetadataExtractionError> {
    let parsed_solc_version =
        semver::Version::parse(&solc_version).map_err(InvalidSolcVersionError::from)?;

    if parsed_solc_version < FIRST_SOLC_VERSION_SUPPORTED {
        return Err(ContractMetadataExtractionError::UnsupportedSolcVersion(
            UnsupportedSolcVersionError {
                minimum: FIRST_SOLC_VERSION_SUPPORTED,
                actual: parsed_solc_version,
            },
        ));
    }

    let build_model = SolcBuildModel::new(compiler_input, &compiler_output)?;
    let sources = Arc::from(
        build_model
            .file_id_to_source_file
            .values()
            .cloned()
            .collect::<Vec<_>>()
            .into_boxed_slice(),
    );

    let contracts = decode_bytecodes(solc_version, &compiler_output, build_model, &sources)?;
    correct_selectors(&contracts, &compiler_output)?;

    Ok(contracts
        .into_iter()
        .map(|contract_metadata| IdentifiedContract {
            contract_metadata,
            trace_strategy: &SOLC_TRACE_STRATEGY,
        })
        .collect())
}

/// A resolved build model from a Solidity compiler standard JSON output.
#[derive(Debug, Default)]
struct SolcBuildModel {
    // TODO https://github.com/NomicFoundation/edr/issues/759
    /// Maps the contract ID to the contract.
    contract_id_to_contract: IndexMap<u32, Arc<RwLock<Contract>>>,
    /// Maps the file ID to the source file.
    file_id_to_source_file: HashMap<u32, Arc<RwLock<SourceFile>>>,
}

impl SolcBuildModel {
    /// Creates a new instance from the provided compiler input and output.
    pub fn new(
        compiler_input: CompilerInput,
        compiler_output: &CompilerOutput<SolcBytecode>,
    ) -> anyhow::Result<Self> {
        let CompiledContractsAndFiles {
            contract_id_to_contract,
            file_id_to_source_file,
        } = collect_compiled_contracts_and_files(compiler_input, compiler_output)?;

        Ok(SolcBuildModel {
            contract_id_to_contract,
            file_id_to_source_file,
        })
    }
}

impl BuildModel for SolcBuildModel {
    type Artifact = SolcBytecode;

    fn contracts(&self) -> impl Iterator<Item = &Arc<RwLock<Contract>>> {
        self.contract_id_to_contract.values()
    }

    fn decode_instructions(
        &self,
        artifact: &Self::Artifact,
        normalized_code: &[u8],
        is_deployment: bool,
    ) -> anyhow::Result<Vec<Instruction>> {
        let source_maps = uncompress_sourcemaps(&artifact.source_map)?;

        let mut instructions = Vec::new();

        let mut bytes_index = 0;

        while instructions.len() < source_maps.len() {
            let source_map = source_maps
                .get(instructions.len())
                .expect("instructions.len() should be within source_maps bounds");

            let pc = bytes_index;
            let opcode = normalized_code
                .get(pc)
                .expect("pc should be within bytecode bounds");

            let opcode = if let Some(opcode) = OpCode::new(*opcode) {
                opcode
            } else {
                log::debug!("Invalid opcode {opcode} at pc: {pc}");

                // We assume this happens because the source maps point to the metadata region
                // of the bytecode. That means that the actual instructions have
                // already been decoded and we can stop here.
                return Ok(instructions);
            };

            let push_data = if opcode.is_push() {
                let push_data = normalized_code
                    .get(bytes_index..)
                    .expect("bytes_index should be within bytecode bounds")
                    .get(..1 + opcode.info().immediate_size() as usize)
                    .expect("bytecode should have enough bytes for push data");

                Some(push_data.to_vec())
            } else {
                None
            };

            let jump_type = match (opcode, source_map.jump_type) {
                (OpCode::JUMP | OpCode::JUMPI, JumpType::NotJump) => JumpType::InternalJump,
                _ => source_map.jump_type,
            };

            let location = if source_map.location.file == -1 {
                None
            } else {
                if let Some(source_file) =
                    self.source_model_by_file_id(source_map.location.file as u32)
                {
                    Some(SourceLocation::new(
                        source_file,
                        source_map.location.offset as u32,
                        source_map.location.length as u32,
                    ))
                } else {
                    log::warn!(
                        "Failed to find source file for file ID: {}",
                        source_map.location.file
                    );
                    None
                }
            };

            let instruction = Instruction {
                pc: bytes_index as u32,
                opcode,
                jump_type,
                push_data,
                location,
                inline_call_sites: Box::default(),
            };

            instructions.push(instruction);

            bytes_index += 1 + opcode.info().immediate_size() as usize;
        }

        if is_deployment {
            add_unmapped_instructions(&mut instructions, normalized_code)?;
        }

        Ok(instructions)
    }

    fn source_model_by_file_id(&self, file_id: u32) -> Option<&Arc<RwLock<SourceFile>>> {
        self.file_id_to_source_file.get(&file_id)
    }
}

#[cfg(test)]
mod tests {
    use crate::artifacts::{
        solc::extract_solc_contract_metadata, CompilerInput, CompilerOutput, SolcBytecode,
    };

    fn fixture() -> (CompilerInput, CompilerOutput<SolcBytecode>) {
        let input: CompilerInput =
            serde_json::from_str(include_str!("../../fixtures/compiler_input.json")).unwrap();
        let output: CompilerOutput<SolcBytecode> =
            serde_json::from_str(include_str!("../../fixtures/compiler_output.json")).unwrap();
        (input, output)
    }

    #[test]
    fn test_solc_fixture_decodes() {
        let (input, output) = fixture();
        let result = extract_solc_contract_metadata("0.8.0".to_string(), input, output);
        assert!(
            result.is_ok(),
            "solc fixture should still decode: {:?}",
            result.err()
        );
    }
}
