//! solx-specific build model types.

use std::{
    collections::HashMap,
    sync::{Arc, OnceLock},
};

use indexmap::IndexMap;
use parking_lot::RwLock;

use super::{
    collect_ast_spans, BuildInfo, BuildInfoOutput, BuildInfoWithOutput, CompilerInput,
    CompilerMetadataParseError, CompilerOutput, ContractMetadataExtractionError,
    InvalidSolcVersionError, JsonSource, SolxBytecode, SplitCompilerMetadataParseError,
    UnsupportedSolcVersionError,
};
use crate::{
    artifacts::solc::{collect_compiled_contracts_and_files, CompiledContractsAndFiles},
    build_model::{BuildModel, Contract, Instruction, SourceFile},
    compiler::{correct_selectors, decode_bytecodes, FIRST_SOLC_VERSION_SUPPORTED},
    contracts_identifier::IdentifiedContract,
    debug_info::dwarf,
    trace_strategy::SOLX_TRACE_STRATEGY,
};

/// Parses the compiler metadata generated by solx as a single JSON file,
/// extracts the contained compiler metadata, and returns a vector of identified
/// contracts.
pub fn parse_solx_compiler_metadata(
    metadata: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, CompilerMetadataParseError> {
    let BuildInfoWithOutput {
        _format,
        id: _,
        solc_version,
        solc_long_version: _,
        input,
        output,
    } = metadata.parse_json::<BuildInfoWithOutput<SolxBytecode>>()?;

    extract_solx_contract_metadata(solc_version, input, output)
        .map_err(CompilerMetadataParseError::from)
}

/// Parses the compiler metadata generated by solx as two separate JSON files
/// (one for the input and one for the output), extracts the contained compiler
/// metadata, and returns a vector of identified contracts.
pub fn parse_split_solx_compiler_metadata(
    input: impl JsonSource,
    output: impl JsonSource,
) -> Result<Vec<IdentifiedContract>, SplitCompilerMetadataParseError> {
    let BuildInfo {
        _format,
        id: input_id,
        solc_version,
        solc_long_version: _,
        input,
    } = input.parse_json::<BuildInfo>()?;

    let BuildInfoOutput {
        _format,
        id: output_id,
        output,
    } = output.parse_json::<BuildInfoOutput<SolxBytecode>>()?;

    if input_id != output_id {
        return Err(SplitCompilerMetadataParseError::IdMismatch {
            input_id,
            output_id: output_id.clone(),
        });
    }

    extract_solx_contract_metadata(solc_version, input, output)
        .map_err(SplitCompilerMetadataParseError::from)
}

/// Extracts [`IdentifiedContract`]s from the provided solx compiler input and
/// output.
pub fn extract_solx_contract_metadata(
    solc_version: String,
    compiler_input: CompilerInput,
    compiler_output: CompilerOutput<SolxBytecode>,
) -> Result<Vec<IdentifiedContract>, ContractMetadataExtractionError> {
    let parsed_solc_version =
        semver::Version::parse(&solc_version).map_err(InvalidSolcVersionError::from)?;

    if parsed_solc_version < FIRST_SOLC_VERSION_SUPPORTED {
        return Err(ContractMetadataExtractionError::UnsupportedSolcVersion(
            UnsupportedSolcVersionError {
                minimum: FIRST_SOLC_VERSION_SUPPORTED,
                actual: parsed_solc_version,
            },
        ));
    }

    let build_model = SolxBuildModel::new(compiler_input, &compiler_output)?;
    let sources = Arc::from(
        build_model
            .file_id_to_source_file
            .values()
            .cloned()
            .collect::<Vec<_>>()
            .into_boxed_slice(),
    );

    let contracts = decode_bytecodes(solc_version, &compiler_output, build_model, &sources)?;
    correct_selectors(&contracts, &compiler_output)?;

    Ok(contracts
        .into_iter()
        .map(|contract_metadata| IdentifiedContract {
            contract_metadata,
            trace_strategy: &SOLX_TRACE_STRATEGY,
        })
        .collect())
}

/// A resolved build model from a solx Solidity compiler standard JSON output.
#[derive(Debug)]
pub struct SolxBuildModel {
    /// Per-file AST `src` spans (`file_id` → sorted `(offset, length)`).
    /// The DWARF parser uses this to derive `SourceLocation.length` from a
    /// `(file, line, column)` triple.
    ast_spans: HashMap<u32, Vec<(u32, u32)>>,
    // TODO https://github.com/NomicFoundation/edr/issues/759
    /// Maps the contract ID to the contract.
    contract_id_to_contract: IndexMap<u32, Arc<RwLock<Contract>>>,
    /// Maps the file ID to the source file.
    file_id_to_source_file: Arc<HashMap<u32, Arc<RwLock<SourceFile>>>>,
    /// Lazy reverse-index `source_name` → `file_id`. See
    /// [`Self::name_to_file_id`].
    name_to_file_id: OnceLock<HashMap<String, u32>>,
}

impl SolxBuildModel {
    /// Creates a new instance from the provided compiler input and output.
    pub fn new(
        compiler_input: CompilerInput,
        compiler_output: &CompilerOutput<SolxBytecode>,
    ) -> anyhow::Result<Self> {
        let ast_spans = collect_ast_spans(compiler_output.sources.values());

        let CompiledContractsAndFiles {
            contract_id_to_contract,
            file_id_to_source_file,
        } = collect_compiled_contracts_and_files(compiler_input, compiler_output)?;

        Ok(Self {
            ast_spans,
            contract_id_to_contract,
            file_id_to_source_file: Arc::new(file_id_to_source_file),
            name_to_file_id: OnceLock::new(),
        })
    }

    #[cfg(test)]
    pub(crate) fn with_sources(
        file_id_to_source_file: HashMap<u32, Arc<RwLock<SourceFile>>>,
    ) -> Self {
        Self {
            ast_spans: HashMap::new(),
            contract_id_to_contract: IndexMap::new(),
            file_id_to_source_file: Arc::new(file_id_to_source_file),
            name_to_file_id: OnceLock::new(),
        }
    }

    pub fn file_id_by_name(&self, source_name: &str) -> Option<u32> {
        self.name_to_file_id().get(source_name).copied()
    }

    /// Reverse-index of `file_id_to_source_file` keyed by source name.
    /// Lazily populated on first call, reused thereafter.
    pub fn name_to_file_id(&self) -> &HashMap<String, u32> {
        self.name_to_file_id.get_or_init(|| {
            self.file_id_to_source_file
                .iter()
                .map(|(id, file)| (file.read().source_name.clone(), *id))
                .collect()
        })
    }

    /// Smallest (leafmost) AST `(offset, length)` span containing `offset`.
    /// Returns `None` if no span in `ast_spans[file_id]` covers `offset`.
    pub fn smallest_enclosing_span(&self, file_id: u32, offset: u32) -> Option<(u32, u32)> {
        let spans = self.ast_spans.get(&file_id)?;
        let mut best: Option<(u32, u32)> = None;
        for &(span_offset, span_length) in spans {
            if span_offset > offset {
                break;
            }
            if offset < span_offset.saturating_add(span_length)
                && best.is_none_or(|(_, best_len)| span_length < best_len)
            {
                best = Some((span_offset, span_length));
            }
        }
        best
    }
}

impl BuildModel for SolxBuildModel {
    type Artifact = SolxBytecode;

    fn contracts(&self) -> impl Iterator<Item = &Arc<RwLock<Contract>>> {
        self.contract_id_to_contract.values()
    }

    fn decode_instructions(
        &self,
        artifact: &Self::Artifact,
        normalized_code: &[u8],
        is_deployment: bool,
    ) -> anyhow::Result<Vec<Instruction>> {
        dwarf::decode_instructions(normalized_code, &artifact.debug_info, self, is_deployment)
            .map_err(Into::into)
    }

    fn source_model_by_file_id(&self, file_id: u32) -> Option<&Arc<RwLock<SourceFile>>> {
        self.file_id_to_source_file.get(&file_id)
    }
}

#[cfg(test)]
mod tests {
    use crate::artifacts::{
        solx::extract_solx_contract_metadata, CompilerInput, CompilerOutput, SolxBytecode,
    };

    fn solx_fixture() -> (CompilerInput, CompilerOutput<SolxBytecode>) {
        let mut input: CompilerInput =
            serde_json::from_str(include_str!("../../fixtures/solx_compiler_input.json")).unwrap();

        input.sources.get_mut("Counter.sol").unwrap().content =
            include_str!("../../fixtures/sources/Counter.sol").to_string();

        let output: CompilerOutput<SolxBytecode> =
            serde_json::from_str(include_str!("../../fixtures/solx_compiler_output.json")).unwrap();

        (input, output)
    }

    #[test]
    fn test_solx_fixture_decodes_via_dwarf() {
        let (input, output) = solx_fixture();

        let bytecodes = extract_solx_contract_metadata("0.8.34".to_string(), input, output)
            .expect("solx fixture must decode through the DWARF parser");

        // Creation + runtime.
        assert!(
            bytecodes.len() >= 2,
            "expected at least 2 ContractMetadata for the Counter contract, got {}",
            bytecodes.len()
        );
        // PC → line assertions live in `crate::debug_info::dwarf::tests`.
    }
}
