[package]
name = "foundry-common"

version.workspace = true
edition.workspace = true

[dependencies]
foundry-block-explorers = { workspace = true, features = ["foundry-compilers"] }
foundry-compilers.workspace = true

alloy-chains.workspace = true
alloy-consensus.workspace = true
alloy-dyn-abi = { workspace = true, features = ["arbitrary", "eip712"] }
alloy-json-abi.workspace = true
alloy-primitives = { workspace = true, features = ["serde", "getrandom", "arbitrary", "rlp"] }
alloy-rpc-types-engine.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-client.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-transport-http = { workspace = true, features = ["reqwest", "reqwest-rustls-tls"] }
alloy-transport-ws.workspace = true
alloy-transport-ipc.workspace = true
alloy-json-rpc.workspace = true
alloy-pubsub.workspace = true
alloy-sol-types.workspace = true

tower.workspace = true

dunce.workspace = true
eyre.workspace = true
reqwest.workspace = true
semver = "1"
serde_json.workspace = true
serde.workspace = true
thiserror = "1"
tokio.workspace = true
tracing.workspace = true
url = "2"
walkdir = "2"
yansi.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
foundry-macros.workspace = true
similar-asserts.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
