[package]
name = "edr_macros"

version.workspace = true
edition.workspace = true

[lib]
proc-macro = true
# proc-macro tests aren't fully supported by cargo-nextest archives
test = false
doc = false

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
proc-macro-error = "1"

[lints]
workspace = true
