[package]
name = "edr_tool_cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cfg-if = "1.0.0"
clap.workspace = true
derive-where.workspace = true
difference = { version = "2.0.0", default-features = false }
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_chain_l1.workspace = true
edr_chain_spec_provider.workspace = true
edr_defaults.workspace = true
edr_generic.workspace = true
edr_napi_core.workspace = true
edr_op = { workspace = true, features = ["test-utils"] }
edr_provider = { workspace = true, features = ["test-utils"] }
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
edr_rpc_spec.workspace = true
edr_scenarios.workspace = true
edr_solidity.workspace = true
edr_test_block_replay.workspace = true
flate2 = "1.0.28"
indicatif = { version = "0.17.7", features = ["rayon"] }
mimalloc = { version = "0.1.39", default-features = false }
op-revm.workspace = true
parking_lot.workspace = true
reqwest = { version = "0.11.12", features = ["blocking"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio = "1.33.0"
toml = { workspace = true, features = ["preserve_order"] }
tracing = { version = "0.1.37", features = ["attributes", "std"], optional = true }
tracing-flame = { version = "0.2.0", default-features = false, features = ["smallvec"], optional = true }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["ansi", "env-filter", "fmt", "parking_lot", "smallvec", "std"], optional = true }
walkdir = { version = "2.4.0", features = [] }

[features]
tracing = ["dep:tracing", "dep:tracing-flame", "dep:tracing-subscriber", "edr_provider/tracing"]

[lints]
workspace = true
