[package]
name = "edr_solidity_collector_eip712"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-dyn-abi = { workspace = true, features = ["eip712"] }
crossbeam-channel.workspace = true
derive-where.workspace = true
edr_solidity_parser_slang.workspace = true
edr_utils_sync.workspace = true
rayon = "1"
semver.workspace = true
slang_solidity_v2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
