[package]
name = "edr_eip1559"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-eips.workspace = true

[dev-dependencies]
edr_chain_l1.workspace = true

[lints]
workspace = true
