[package]
name = "edr_test_utils"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
foundry-common.workspace = true
foundry-compilers = { workspace = true, features = ["project-util"] }

fd-lock = "4.0.0"
once_cell = "1"
regex = "1"
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
rand.workspace = true

[lints]
workspace = true
