[package]
name = "edr_test_utils"
version.workspace = true
edition.workspace = true

[dependencies]
edr_common.workspace = true
edr_eth = { version = "0.3.5", path = "../edr_eth", features = ["rand", "serde"] }
fd-lock = "4.0.0"
foundry-compilers = { workspace = true, features = ["project-util"] }
hex = "0.4.3"
once_cell = "1"
rand.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
