[package]
name = "edr_test_utils"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }
