[package]
name = "edr_test_utils"
version.workspace = true
edition.workspace = true

[dependencies]
edr_eth = { version = "0.3.5", path = "../edr_eth", features = ["rand", "serde"] }
hex = "0.4.3"
k256 = { version = "0.13.1", default-features = false, features = ["arithmetic", "ecdsa", "pkcs8", ] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true


[lints]
workspace = true
