[package]
name = "edr_test_utils"
version = "0.3.5"
edition = "2021"

[dependencies]
edr_eth = { version = "0.3.5", path = "../edr_eth", features = ["rand", "serde"] }
hex = "0.4.3"
k256 = { version = "0.13.1", default-features = false, features = ["arithmetic", "ecdsa", "pkcs8", ] }
serde = { version = "1.0.209", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.127" }


[lints]
workspace = true
