[package]
name = "tools"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cfg-if = "1.0.0"
clap = { version = "3.2.20", features = ["derive"] }
derive-where.workspace = true
difference = { version = "2.0.0", default-features = false }
edr_block_header.workspace = true
edr_chain_l1.workspace = true
edr_defaults.workspace = true
edr_evm = { workspace = true, features = ["test-utils", "tracing"] }
edr_evm_spec.workspace = true
edr_generic.workspace = true
edr_napi_core.workspace = true
edr_op = { workspace = true, features = ["test-utils"] }
edr_provider = { workspace = true, features = ["test-utils"] }
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
edr_solidity.workspace = true
edr_scenarios.workspace = true
flate2 = "1.0.28"
indicatif = { version = "0.17.7", features = ["rayon"] }
mimalloc = { version = "0.1.39", default-features = false }
parking_lot.workspace = true
reqwest = { version = "0.11.12", features = ["blocking"] }
serde_json.workspace = true
serde.workspace = true
tempfile = "3.7.1"
tokio = "1.33.0"
tracing = { version = "0.1.37", features = ["attributes", "std"], optional = true }
tracing-flame = { version = "0.2.0", default-features = false, features = ["smallvec"], optional = true }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["ansi", "env-filter", "fmt", "parking_lot", "smallvec", "std"], optional = true }
toml = { version = "0.5.9", default-features = false }
walkdir = { version = "2.4.0", features = [] }

[features]
tracing = ["dep:tracing", "dep:tracing-flame", "dep:tracing-subscriber", "edr_evm/tracing", "edr_provider/tracing"]

[lints]
workspace = true
