[package]
name = "tools"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cfg-if = "1.0.0"
clap = { version = "3.2.20", features = ["derive"] }
derive-where.workspace = true
difference = { version = "2.0.0", default-features = false }
edr_defaults = { version = "0.3.5", path = "../edr_defaults" }
edr_eth = { version = "0.3.5", path = "../edr_eth" }
edr_evm = { version = "0.3.5", path = "../edr_evm", features = ["test-utils", "tracing"] }
edr_generic = { version = "0.3.5", path = "../edr_generic" }
edr_napi_core = { path = "../edr_napi_core" }
edr_op = { path = "../edr_op", features = ["test-utils"] }
edr_provider = { path = "../edr_provider", features = ["test-utils"] }
edr_rpc_eth = { version = "0.3.5", path = "../edr_rpc_eth" }
edr_solidity = { version = "0.3.5", path = "../edr_solidity" }
edr_scenarios = { version = "0.3.5", path = "../edr_scenarios" }
flate2 = "1.0.28"
indicatif = { version = "0.17.7", features = ["rayon"] }
mimalloc = { version = "0.1.39", default-features = false }
parking_lot = { version = "0.12.1", default-features = false }
reqwest = { version = "0.11.12", features = ["blocking"] }
serde_json.workspace = true
serde.workspace = true
tempfile = "3.7.1"
tokio = "1.33.0"
tracing = { version = "0.1.37", features = ["attributes", "std"], optional = true }
tracing-flame = { version = "0.2.0", default-features = false, features = ["smallvec"], optional = true }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["ansi", "env-filter", "fmt", "parking_lot", "smallvec", "std"], optional = true }
toml = { version = "0.5.9", default-features = false }
walkdir = { version = "2.4.0", features = [] }
foundry-evm-core = { path = "../foundry/evm/core" }
alloy-json-abi.workspace = true
csv = "1.3.0"
git2 = "0.18.3"
rayon = "1.8.0"
regex = "1.10.0"

[features]
tracing = ["dep:tracing", "dep:tracing-flame", "dep:tracing-subscriber", "edr_eth/tracing", "edr_evm/tracing", "edr_provider/tracing"]

[lints]
workspace = true
