[package]
name = "edr_runtime_spec"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-rlp.workspace = true
edr_block_api.workspace = true
edr_block_builder_api.workspace = true
edr_block_header.workspace = true
edr_block_remote.workspace = true
edr_chain_config.workspace = true
edr_chain_spec.workspace = true
edr_database_components.workspace = true
edr_eip1559.workspace = true
edr_evm_spec.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_receipt_spec.workspace = true
edr_rpc_eth.workspace = true
edr_rpc_spec.workspace = true
edr_state_api.workspace = true
edr_transaction.workspace = true

[lints]
workspace = true
