[package]
name = "edr_state_fork"
version.workspace = true
edition.workspace = true

[dependencies]
derive-where.workspace = true
edr_primitives.workspace = true
edr_rpc_eth.workspace = true
edr_rpc_spec.workspace = true
edr_state_api.workspace = true
edr_state_persistent_trie.workspace = true
edr_state_remote.workspace = true
edr_utils.workspace = true
parking_lot.workspace = true
serde.workspace = true
tokio.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
edr_chain_l1.workspace = true
edr_eth.workspace = true
edr_test_utils.workspace = true
tempfile.workspace = true

[features]
test-remote = []
tracing = ["dep:tracing"]

[lints]
workspace = true
