[package]
name = "edr_block_api"
version.workspace = true
edition.workspace = true

[dependencies]
auto_impl.workspace = true
edr_block_header.workspace = true
edr_primitives.workspace = true

[lints]
workspace = true
