[package]
name = "edr_block_api"
version.workspace = true
edition.workspace = true

[dependencies]
auto_impl.workspace = true
edr_block_header.workspace = true
edr_chain_spec.workspace = true
edr_eip1559.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_state_api.workspace = true
thiserror.workspace = true

[lints]
workspace = true
