name: Setup Rust toolchain
description: Sets up the Rust toolchain
inputs:
  toolchain:
    description: The Rust toolchain to use
    required: false
    default: stable
  components:
    description: Comma-separated list of components to install
    required: false
    default: rustfmt, clippy
  override:
    description: Whether to override the existing toolchain
    required: false

runs:
  using: composite
  steps:
    - name: Install Rust (${{ inputs.toolchain }})
      shell: bash
      run: |
        set -e

        rustup install ${{ inputs.toolchain }} --profile minimal

        # Split the components string into an array using IFS
        IFS=',' read -ra COMPONENTS <<< "${{ inputs.components }}"
        for component in "${COMPONENTS[@]}"; do
          echo "Installing component: $component"
          rustup component add $component --toolchain ${{ inputs.toolchain }}
        done

        if [ "${{ inputs.override }}" == "true" ]; then
            echo "Overriding existing toolchain"
            rustup override set ${{ inputs.toolchain }}
        fi
