[package]
name = "edr_eip1559"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-eips.workspace = true

[dev-dependencies]
edr_evm_spec.workspace = true

[lints]
workspace = true
