[package]
name = "edr_block_remote"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_evm_spec.workspace = true
edr_primitives.workspace = true
edr_rpc_eth.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
