[package]
name = "edr_block_remote"
version.workspace = true
edition.workspace = true

[dependencies]
derive-where.workspace = true
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_chain_spec.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
edr_rpc_spec.workspace = true
edr_utils.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lints]
workspace = true
