[package]
name = "edr_trie"
version.workspace = true
edition.workspace = true

[dependencies]
edr_primitives.workspace = true
hash-db = { version = "0.15.2", default-features = false, features = ["std"] }
hash256-std-hasher = { version = "0.15.2", default-features = false, features = ["std"] }
sha3 = { workspace = true, features = ["std"] }
triehash = { version = "0.8.4", default-features = false, features = ["std"] }

[lints]
workspace = true
