name: Check generated files

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  edr-op-chain-configs:
    name: Check that op-chain config files are up to date
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout EDR repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Rust & install nightly rustfmt
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run op-chain-config command that updates chains config
        run: cargo op-chain-config

      - name: Check that there are no uncommitted changes
        run: cargo op-chain-config -- --check

      - name: Notify failure
        if: failure()
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          webhook: ${{ secrets.GH_ACTION_NOTIFICATIONS_SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "workflow_name": "${{ github.workflow }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
