name: EDR NPM release

x-docker-options: &docker_options "--user 0:0 \
  -v ${{ github.workspace }}/.cargo/registry/index:/root/.cargo/registry/index \
  -v ${{ github.workspace }}/.cargo/registry/cache:/root/.cargo/registry/cache \
  -v ${{ github.workspace }}/.cargo/git:/root/.cargo/git \
  -v ${{ github.workspace }}/target:/build/target \
  -v ${{ github.workspace }}:/build \
  -w /build/crates/edr_napi"

x-build-gnu: &build_gnu |
  set -e
  apt-get update
  apt-get install -y curl ca-certificates build-essential pkg-config python3 make git perl cmake
  curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
  export PATH="/root/.cargo/bin:$PATH"
  corepack enable
  npm i -g pnpm@10.17.1
  pnpm -v
  pnpm install --frozen-lockfile --prefer-offline
  pnpm run build --strip

x-build-musl: &build_musl |
  set -e
  apk add --no-cache build-base python3 make git pkgconfig openssl openssl-dev ca-certificates curl bash perl cmake
  curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
  export PATH="/root/.cargo/bin:$PATH"
  corepack enable
  npm i -g pnpm@10.17.1
  pnpm -v
  pnpm install --frozen-lockfile --prefer-offline
  pnpm run build --strip

env:
  DEBUG: napi:*
  APP_NAME: edr
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  NUMBER_OF_TARGETS: 7
permissions:
  contents: write
  id-token: write
on:
  push:
    # pre-releases will be triggered in any of these branches
    # production releases will only be triggered for `main`
    branches:
      - main
      - prerelease
      - hh2
      - feat/solidity-tests
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - "**/*.gitignore"
      - .editorconfig
      - docs/**
  pull_request: null
  workflow_dispatch:

jobs:
  build:
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
            build: pnpm run build --strip

          - host: macos-14
            target: aarch64-apple-darwin
            build: pnpm run build --strip

          - host: windows-2022
            target: x86_64-pc-windows-msvc
            build: pnpm run build --strip

          - host: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            docker: node:20-bullseye-slim
            flavor: gnu

          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            docker: node:20-bullseye-slim
            flavor: gnu

          - host: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            docker: node:20-alpine3.20
            flavor: musl

          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            docker: node:20-alpine3.20
            flavor: musl
    defaults:
      run:
        working-directory: ./crates/edr_napi

    steps:
      - uses: actions/checkout@v5

      - name: Check number of targets
        shell: bash
        run: |
          echo "Number of build jobs: ${{ strategy.job-total }}"
          echo "Expected number of build jobs: $NUMBER_OF_TARGETS"
          test ${{ strategy.job-total }} -eq "$NUMBER_OF_TARGETS"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
          components: rust-src

      - name: Setup node and pnpm
        if: ${{ !matrix.settings.docker }}
        uses: ./.github/actions/setup-node

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Install dependencies
        if: ${{ !matrix.settings.docker }}
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build (non-docker)
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash

      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: *docker_options
          run: ${{ matrix.settings.flavor == 'gnu' && '<< *build_gnu >>' || '<< *build_musl >>' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          # The upload artifact action doesn't respect the working directory setting. Unclear if this is a bug or not
          # https://github.com/actions/upload-artifact/issues/294
          path: ./crates/edr_napi/${{ env.APP_NAME }}.*.node
          if-no-files-found: error

  test-macOS-windows-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
          - host: macos-14
            target: aarch64-apple-darwin
          - host: windows-2022
            target: x86_64-pc-windows-msvc
        node:
          - "20"
          - "22"
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: ./crates/edr_napi
    steps:
      - uses: actions/checkout@v5
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ./crates/edr_napi/
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        run: pnpm testNoBuild

  test-linux-x64-gnu-binding:
    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - "20"
          - "22"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: ./crates/edr_napi/
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        # Setting CI=1 is important to make PNPM install non-interactive
        # https://github.com/pnpm/pnpm/issues/6615#issuecomment-1656945689
        run: docker run --rm  -e CI=1 -v $(pwd):/build -w /build/crates/edr_napi node:${{ matrix.node }} bash -c "wget -qO- 'https://unpkg.com/@pnpm/self-installer' | node; pnpm testNoBuild"
  test-linux-x64-musl-binding:
    name: Test bindings on x86_64-unknown-linux-musl - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - "20"
          - "22"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline --libc=musl
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bindings-x86_64-unknown-linux-musl
          path: ./crates/edr_napi/
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        run: docker run --rm  -e CI=1 -v $(pwd):/build -w /build/crates/edr_napi node:${{ matrix.node }}-alpine sh -c "wget -qO- 'https://unpkg.com/@pnpm/self-installer' | node; pnpm testNoBuild"
  test-linux-aarch64-gnu-binding:
    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - "20"
          - "22"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bindings-aarch64-unknown-linux-gnu
          path: ./crates/edr_napi/
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline --cpu=arm64 --libc=glibc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Setup and run tests
        uses: addnab/docker-run-action@v3
        with:
          image: node:${{ matrix.node }}
          options: "--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build/crates/edr_napi -e CI=1"
          run: |
            wget -qO- 'https://unpkg.com/@pnpm/self-installer' | node
            set -e
            pnpm testNoBuild
            ls -la
  test-linux-aarch64-musl-binding:
    name: Test bindings on aarch64-unknown-linux-musl - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - "20"
          - "22"
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bindings-aarch64-unknown-linux-musl
          path: ./crates/edr_napi/
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline --cpu=arm64 --libc=musl
      - name: Setup and run tests
        uses: addnab/docker-run-action@v3
        with:
          image: node:${{ matrix.node }}-alpine
          options: "--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build/crates/edr_napi -e CI=1"
          run: |
            wget -qO- 'https://unpkg.com/@pnpm/self-installer' | node
            set -e
            pnpm testNoBuild
  check_commit:
    name: Check commit
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request' || github.event.pull_request.author_association == 'OWNER' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'COLLABORATOR'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check if commit message is a release commit
        id: check_commit
        # Must match commit check in publish step
        run: |
          if git log -1 --pretty=%B | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            echo "Check commit: matches"
            echo "match=true" >> "$GITHUB_OUTPUT"
          else
            echo "Check commit: no match"
            echo "match=false" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      match: ${{ steps.check_commit.outputs.match }}
  publish:
    name: Publish
    environment: edr-release
    runs-on: ubuntu-24.04
    needs:
      - check_commit
      - test-macOS-windows-binding
      - test-linux-x64-gnu-binding
      - test-linux-x64-musl-binding
      - test-linux-aarch64-gnu-binding
      - test-linux-aarch64-musl-binding
    # Only run workflow if the commit message is a release commit.
    if: ${{ needs.check_commit.outputs.match == 'true' }}
    defaults:
      run:
        working-directory: ./crates/edr_napi
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./crates/edr_napi/artifacts
      - name: Check number of artifacts
        shell: bash
        run: |
          tree artifacts
          # get number of artifacts with unique names
          NUMBER_OF_ARTIFACTS=$(ls -1q artifacts/*/*.node | xargs -n 1 basename | sort | uniq | wc -l)
          echo "Number of unique artifacts: $NUMBER_OF_ARTIFACTS"
          echo "Expected number of unique artifacts: $NUMBER_OF_TARGETS"
          test "$NUMBER_OF_ARTIFACTS" -eq "$NUMBER_OF_TARGETS"
      - name: Install sponge
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
      - name: Move artifacts
        run: pnpm artifacts
      - name: Publish
        run: |
          if git log -1 --pretty=%B | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+-";
          then
            if [ "${{ github.event_name }}" = "push" ]; then
              echo "Publishing pre-release"
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              pnpm publish --no-git-checks --provenance --tag next --access public
            else
              echo "Trying to publish a pre-release from a branch that is not 'main' or 'prerelease'"
            fi
          elif git log -1 --pretty=%B | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+\s*";
          then
            if [ "$GITHUB_REF" == "refs/heads/main" -o "$GITHUB_REF" == "refs/heads/hh2" ]; then
              echo "Publishing release"
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              pnpm publish --no-git-checks --provenance --access public
            else
              echo "Trying to publish a release from a branch that is not 'main' or 'h2'"
            fi
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.IGNORED_ORG_NPM_TOKEN }}
