name: Open changesets PR

on:
  push:
    branches:
      - main
      - ci/improve-changeset-release

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install sponge # Needed for prepublish script
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils

      - name: Get version from package.json
        id: get-version
        run: |
          STATUS="$RUNNER_TEMP/status.json"
          pnpm changeset status --output "$(realpath --relative-to=. "$STATUS")"
          VERSION="$(jq -r '.releases[] | select(.name == "@nomicfoundation/edr").newVersion' "$STATUS")"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run Prepublish before changesets
        run: |
          cd ./crates/edr_napi
          bash ../../scripts/prepublish.sh
          cd ../..

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "TESTING CI - edr-${{ steps.get-version.outputs.version }}"
          commit: "testing ci edr-${{ steps.get-version.outputs.version }}"
        env:
          # If the default GITHUB_TOKEN is used, checks will not run in release PRs.
          # To have checks run, set up CHANGESETS_TOKEN in repo secrets with read/write
          # permission for Contents and Pull requests scopes.
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN || secrets.GITHUB_TOKEN }}
